### ISSUE TITLE
Scastie is Scala + {WHAT???} in your browser.

### ISSUE THREAD

**Issue by dscotese** [scala/scala-lang#1008]
sbt doesn't mean anything to me.  I'm good with Windows, DOS, Linux, Java, Javascript, SQL, etc., but I have no idea what sbt is.  Perhaps that should be a link.  It could link to https://www.scala-sbt.org/ and instead of writing "Scastie is Scala + sbt in your browser", write "Scastie is Scala + the Scala Build Tool ([sbt](https://www.scala-sbt.org/) in your browser." Or just "Scastie is Scala + [sbt](https://www.scala-sbt.org/) in your browser."

Don't you love issues that are so simple to solve? :-)

**Comment by julienrf** [comment]
sbt is probably well known in the Scala community, but we could add a link to scala-sbt.org, indeed. Are you interested in making a PR for that?

**Comment by dscotese** [comment]
Yes, I am.  I'm interested in learning Scala and contributing more to projects on Github.  I'm finding that a lot of what I want to do requires me to fork over more money to Microsoft (because I like using their Windows product).  However, I want to get used to Linux and switch my whole life away from proprietary solutions.  Anyway, sorry for the off-topic.  I think I need to find the file to alter, alter it, commit it to my own fork, and then I can make the PR, right?  I'll get to it eventually :-)

**Comment by dscotese** [comment]
I just made #1009 Thanks!
