### ISSUE TITLE
Missing copyright year on license page

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1023]
whatever mechanism is supposed to make "2019" show up automatically at https://www.scala-lang.org/license/ (and perhaps elsewhere on the site? not sure) isn't working, I just see

<img width="316" alt="Screen Shot 2019-03-17 at 11 36 45 PM" src="https://user-images.githubusercontent.com/161079/54498991-8bc72f00-490d-11e9-9b83-86d8f525b2c0.png">

**Comment by sjrd** [comment]
There's a `<span class="current-year"> </span>` in there, which suggests it was supposed to filled in by some JS. However `git grep current-year` only shows the two occurrences of the `<span>`.

**Comment by SethTisue** [comment]
got broke by 62b2561b0e90cf10cbc74d318c657c18812211a4 I think
