### ISSUE TITLE
Typo on downloads page

### ISSUE THREAD

**Issue by Martomate** [scala/scala-lang#1028]
At the bottom of the downloads page (https://www.scala-lang.org/download/index.html#other-releases) under the License header it says "The Scala distribution is released under the ." which seems to be lacking the name of the license.

I'm not familiar with this repo though, so I don't know how to fix it.

**Comment by Philippus** [comment]
maybe this broke in https://github.com/scala/scala-lang/pull/1027 @dwijnand ?

**Comment by dwijnand** [comment]
Actually, I inadvertently broke this in #1019.  Proposing a fix in #1029.
