### ISSUE TITLE
broken link to Citizen Code of Conduct

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1038]
as reported at https://twitter.com/LechGlowiak/status/1123658111062089729

perhaps it's a transient problem? let's give it a few days to be resolved and if it isn't we can change the link to https://web.archive.org/web/20190425220720/http://citizencodeofconduct.org/

**Comment by lrytz** [comment]
Seems the source is https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md

**Comment by dwijnand** [comment]
It's back.
