### ISSUE TITLE
404 in Lukas's blog post

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1164]
https://www.scala-lang.org/blog/2016/07/08/trait-method-performance.html

https://travis-ci.org/github/scala/scala-lang/builds/734818130

```
- ./_site/blog/2016/07/08/trait-method-performance.html
*  External link https://github.com/lrytz/benchmarks/blob/master/src/main/java/traitEncodings/InterfaceManyMembers.java failed: 404 No error
htmlproofer 3.10.2 | Error:  HTML-Proofer found 1 failure!
```

@lrytz can you suggest a suitable replacement URL?

**Comment by som-snytt** [comment]
You mean like https://media.giphy.com/media/4560Nv2656Gv0Lvp9F/giphy.gif ?

**Comment by SethTisue** [comment]
ping @lrytz

**Comment by lrytz** [comment]
restored it.
