### ISSUE TITLE
Improve formatting for release notes pages

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#119]
![](https://f.cloud.github.com/assets/65551/1165001/09de78ea-2064-11e3-9ffa-11a44728a188.png)
![](https://f.cloud.github.com/assets/65551/1164994/e62d90a2-2063-11e3-9477-ab4cc26f6456.png)
![](https://f.cloud.github.com/assets/65551/1164996/ee3b2c3c-2063-11e3-913a-94f6c6884536.png)

Discussed in #117

**Comment by SethTisue** [comment]
we are using a newer markdown engine now. recent release notes don't use tables. and I'm not aware of any recent problems with inline code blocks. so I'm tentatively closing this.
