### ISSUE TITLE
Atom XML namespace must be http not https

### ISSUE THREAD

**Issue by lunaryorn** [scala/scala-lang#1197]
Commit https://github.com/scala/scala-lang/commit/80b2437dc43bf34da8e226ec9e72335f314c05dd changed the Atom `xmlns` in `feed/blog.xml` and `feed/index.xml` to from `http://www.w3.org/2005/Atom` to `https`://www.w3.org/2005/Atom`.

This breaks my RSS reader because the namespace is no longer valid; Atom must be `http://www.w3.org/2005/Atom`, see e.g. <https://tools.ietf.org/html/rfc4287#section-1.2>

**Comment by SethTisue** [comment]
Oops! Care to PR the fix?

**Comment by lunaryorn** [comment]
Will do 👍

Am 25. Dezember 2020 15:49:41 MEZ schrieb Seth Tisue <notifications@github.com>:

**Comment by lunaryorn** [comment]
@SethTisue See #1198
