### ISSUE TITLE
Explain how to run a Scala 3 program compiled on the command line

### ISSUE THREAD

**Issue by lrytz** [scala/scala-lang#1250]
Cross-posting from gitter before I can't find my own message anymore.

https://www.scala-lang.org/download/scala3.html suggests `cs install scala3-compiler` and `cs install scala3-repl` to install, and `scala3-compiler test.scala` to compile something on the command line. But it doesn't say how to run the compiled program.

If I have `@main def hello(): Unit = ...`, then `scala3-repl hello` just opens the REPL. `java -cp $(cs fetch -p scala3-repl):. hello` works, is there anything simpler?

**Comment by lrytz** [comment]
Duplicate of https://github.com/lampepfl/dotty/issues/12811

**Comment by bjornregnell** [comment]
This is a showstopper for me to use cs in my teaching. And there is no .msi for Scala 3 so I'm more or less stuck (manually unpackaging a zip and going into environment variables to fiddle with path etc in Windows is not very attractive beginner programmer user experience...)

**Comment by bjornregnell** [comment]
See also https://github.com/lampepfl/dotty/issues/12502

**Comment by bjornregnell** [comment]
See also https://github.com/scala/scala-lang/issues/1248

**Comment by bjornregnell** [comment]
@lrytz  Is this really a duplicate of https://github.com/lampepfl/dotty/issues/12811? 
A runner does not have to depend on cursier, and the download page should explain how to run a Scala 3 program IMHO.

**Comment by lrytz** [comment]
I closed this to avoid having too many tickets for the same underlying issue. I assume when the coursier issue (https://github.com/coursier/coursier/issues/2058) gets fixed the website will be updated too. But I we can re-open it if desired.

Note that the `scala` bash script from the archive on https://github.com/lampepfl/dotty/releases/tag/3.0.0 acts as runner script or repl launcher, depending on the arguments. But given how low it appears on the download page I don't think anyone is using that.

**Comment by bjornregnell** [comment]
I'm using it :)

Ok; good to reduce overlap among issues. 

This also depends on if `cs` can be *the* official thing that can meet "all" use cases... 

I guess one reason for the low usage could be the lack of easy install of Scala 3 on Windows. Do you have some info on the download stats of the Scala 2 .msi?

**Comment by lrytz** [comment]
> I'm using it :)

Nice, sorry about my skepticism :)

> download stats of the Scala 2 .msi?

I didn't manage to get these stats unfortunately. The files are hosted on a S3 bucket at lightbend, and we're not currently processing the access logs.
