### ISSUE TITLE
Scala Lang formal language definition

### ISSUE THREAD

**Issue by CG-SS** [scala/scala-lang#1257]
Is there anywhere I could find the Scala Lang formal definition?

**Comment by bishabosha** [comment]
is this what you are looking for? https://scala-lang.org/files/archive/spec/2.13/

You can find it from scala-lang.org by going "Documentation" > "Language Spec"

**Comment by CG-SS** [comment]
Yes, that's exactly what I'm looking for, thank you very much!

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions
