### ISSUE TITLE
Home page online courses UX improvement

### ISSUE THREAD

**Issue by ChloeLiang** [scala/scala-lang#1266]
### Actual

It's hard to tell the Coursera and Edx icon can be clicked.

When I browse the online courses section, I initially thought the whole card or course title is clickable. It takes me some time to figure out only the icons are clickable.

### Expected

Improve the UX to attract user's attention on the icon. For example, make the icon larger when user moves the mouse on the card.

https://user-images.githubusercontent.com/28077042/128587887-9efd70ac-1aca-4a4f-9870-b00367069a19.mov

**Comment by julienrf** [comment]
Hey @ChloeLiang, thanks for reporting, I think you make a good point! Would you be interested in contributing a fix?

**Comment by ChloeLiang** [comment]
@julienrf Yes, I'll create a PR.
