### ISSUE TITLE
Website changes not publishing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1289]
@fsalvi I merged https://github.com/scala/scala-lang/pull/1288 about 3 hours ago, but it hasn't shown up on the site

Normally I would visit https://scala-webapps.epfl.ch/jenkins/ to troubleshoot, but that URL won't load. Did something change on the server?

**Comment by SethTisue** [comment]
https://github.com/scala/docs.scala-lang seems to be affected as well. Over there, I merged https://github.com/scala/docs.scala-lang/pull/2214 but the changes aren't visible at e.g. https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by fsalvi** [comment]
I had a problem with jenkins. It should be fixed now.

**Comment by SethTisue** [comment]
Indeed! Thank you!
