### ISSUE TITLE
Broken Scala.js fiddle link

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1295]
CI is failing with:

```
Checking 4970 external links...
Ran on 351 files!
- ./_site/blog/2015/02/05/scala-js-no-longer-experimental.html
htmlproofer 3.10.2 | Error:  HTML-Proofer found 1 failure!
  *  External link http://www.scala-js-fiddle.com failed: 403 No error
  *
```

I'd replace it with https://scalafiddle.io , but that seems to be down, as per https://github.com/scalafiddle/scalafiddle-io/issues/57 which has gone unresponded-to for a week

anybody know anything about who might be responsible for that these days? (@sjrd?)

**Comment by sjrd** [comment]
Otto's company has stopped supporting ScalaFiddle a couple weeks ago. The Scala Center did not want to take it over. I'll try to maintain it on my free time, and I should contact Otto again to see how that's done. But remains the question of paying the servers, so I don't know.

**Comment by juaneto** [comment]
> 

Can I help with that in any way?
