### ISSUE TITLE
Scala 2 download buttons don't work

### ISSUE THREAD

**Issue by wes-novack** [scala/scala-lang#1297]
On: https://www.scala-lang.org/download/scala2.html

Clicking on the `DOWNLOAD INTELLIJ` and the `DOWNLOAD SBT` big red buttons results in nothing happening.

Attempted in both Firefox and Chrome web browsers.

**Comment by SethTisue** [comment]
we're hoping #1294 will fix this. looks like @julienrf plans to review it soon.
