### ISSUE TITLE
Note that the bullet in question was taken verbatim from the Citizen Code of Conduct.

### ISSUE THREAD

**Issue by Horlarhold** [scala/scala-lang#1304]
Note that the bullet in question was taken verbatim from the Citizen Code of Conduct.

This change seems to me like a harmless clarification that doesn't alter what I understand to be the intention behind the text.

Regardless, I suggest we not merge it until:

- We wait and see if any other such edits arise from the current community episode, where CoC issues are coming up.
- We run the batch of edits by the major adopters of the code for feedback.

_Originally posted by @SethTisue in https://github.com/scala/scala-lang/issues/1303#issuecomment-968361649_

**Comment by SethTisue** [comment]
What's the purpose of this ticket?
