### ISSUE TITLE
Splash page should link to Discord, not Gitter

### ISSUE THREAD

**Issue by joshlemer** [scala/scala-lang#1306]
The main splash page links to all the legacy gitter channels, but some time ago those became archived and we moved the community chat to Discord. See screenshot below:

![image](https://user-images.githubusercontent.com/5122903/143484721-ca1b7224-0ef9-44f5-b1be-64d459092fbd.png)

**Comment by joshlemer** [comment]
Likewise, the `/community` page should be updated

![image](https://user-images.githubusercontent.com/5122903/143484935-9205b435-ba90-4e3d-8516-c43fedc8a1db.png)

**Comment by joshlemer** [comment]
Oh sorry, seems this is kind of a duplicate of https://github.com/scala/scala-lang/issues/1256

And also factually incorrect -- Gitter rooms are actually still open and somewhat active

**Comment by SethTisue** [comment]
#1256 has been near the top of my queue for a while now, but I _will_ get to it
