### ISSUE TITLE
Website is unreachable

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1327]
https://www.scala-lang.org just hangs

verified via https://downforeveryoneorjustme.com

**Comment by SethTisue** [comment]
@fsalvi any idea what might be going on...?

**Comment by jducoeur** [comment]
Not just the main site -- looks like the entire scala-lang.org domain is hosed, which suggests some sort of network issue?

**Comment by eed3si9n** [comment]
See also https://github.com/scala/scala-lang/issues/1309

Maybe EPFL shutdown inbound traffic again due to log4j or some other perceived threat.

**Comment by alexandru** [comment]
Not sure if it's feasible to change the nameservers, but putting Cloudflare in front could alleviate such downtime, as Cloudflare can cache pages and serve them when the server is unreachable (with a warning), see [their sales pitch](https://www.cloudflare.com/always-online/).

**Comment by fsalvi** [comment]
Hello, I noticed a firewall problem yesterday evening (around 7pm swiss time), but only scastie and scaladex were concerned, not the main website.
This is due, I guess, to a misconfiguration of the EPFL firewall. I opened a (high severity) ticket yesterday, I will let you know asap.

**Comment by fsalvi** [comment]
Everything should be back online now. There was a network routing problem at EPFL.

**Comment by SethTisue** [comment]
thanks Fabien!
