### ISSUE TITLE
when i use iterator, i hope provide patition method like list(1,2,3).patition 

### ISSUE THREAD

**Issue by sungaok** [scala/scala-lang#1359]
code like this ，input
(iter1,iter2)=iterator(1,2,3,4).partion(_>2)
iter1 is iterator(1,2)
iter2 is iterator(3,4)
return tupel value (iter1,iter2)

**Comment by SethTisue** [comment]
please ask about this on https://users.scala-lang.org (or see https://scala-lang.org/community for other options) — this repo is specifically for website issues
