### ISSUE TITLE
One Click Install instructions no longer work

### ISSUE THREAD

**Issue by dnmfarrell** [scala/scala-lang#1361]
As documented here:
https://www.scala-lang.org/2020/06/29/one-click-install.html

Fails with `Error downloading gz+https://github.com/coursier/coursier/releases/download/v2.1.0-M5-18-gfebf9838c/cs-x86_64-pc-linux.gz`. It seems the client is unable to handle gzipped content? This is described in an [issue](https://github.com/coursier/coursier/issues/2362) on the coursier repo.

The fix for me was to run:
```
curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs
chmod +x cs
./cs setup
```
But these instructions are Linux specific.

**Comment by bishabosha** [comment]
do the instructions at https://docs.scala-lang.org/getting-started/index.html work for you? (if you delete all `cs` stuff first)

**Comment by dnmfarrell** [comment]
Yes they do - but note the linked page on this line:

Follow the [instructions to install the cs launcher](https://get-coursier.io/docs/cli-installation) then run:

Already instructs the user to run `./cs setup`. So you could probably drop that from getting-started/index.html.

**Comment by bishabosha** [comment]
Closing as we now have the tabbed design
