### ISSUE TITLE
Cannot get RSS feed

### ISSUE THREAD

**Issue by lunaryorn** [scala/scala-lang#1427]
I cannot use RSS feeds from Scala Lang from the [hosted miniflux](https://miniflux.app/hosting.html) news reader, see https://github.com/miniflux/v2/issues/1606.  According to [its administrator](https://github.com/miniflux/v2/issues/1606#issuecomment-1288374850) scala-lang.org may be blocking linode.

Could you look into this?

**Comment by fsalvi** [comment]
Hello, it could be some firewall issues. I'm waiting for more information and will keep you updated...

**Comment by lunaryorn** [comment]
@fsalvi Thanks 🙏🏿

**Comment by fsalvi** [comment]
Hello,
Unfortunately, as said here:
https://github.com/miniflux/v2/issues/1606
This cannot be fixed (network security policy from EPFL).
