### ISSUE TITLE
Please provide latest version numbers on frontpage

### ISSUE THREAD

**Issue by domdorn** [scala/scala-lang#1430]
I often find myself looking at scala-lang.org and scala-sbt.org just to see which are the latest version numbers of scala 2.12 (for sbt plugins), scala 2.13 and scala 3.x .. at the moment, this is quite cumbersome as I always have to find the right menu item (in this case its "Install" and then find the version. It would be good to have the current version numbers prominently displayed on the frontpage of scala-lang.org ( scala-sbt.org already added it!)

**Comment by SethTisue** [comment]
good idea

**Comment by SethTisue** [comment]
Good idea!

I had initially thought just 3.x and 2.13.x would be enough, but that's a good point about sbt plugins, plus a lot of Spark folks and others are still on 2.12.

I'd suggest descending order, like: 3.2.0, 2.13.10, 2.12.17

And they should be links, though I'm not sure links to what exactly... Jamie would probably have a good handle on that.

**Comment by SethTisue** [comment]
@bishabosha relatedly, this seems questionable:

```
% git grep scalaversion
_config.yml:scalaversion: "2.13.10"
_includes/downloads-scala2.html:          specific versions of Scala</a> on any platform with <code>sdk install scala {{ site.scalaversion }}</code></li>
_layouts/download.html:{% assign currentScalaRelease = site.scalaversion %}
```

**Comment by bishabosha** [comment]
We had said previously in January or so that putting all the scala 2 vs scala 3 versions on the front page was creating some confusion - i.e. which to pick, and at the time there was more than one "recommended" way to install - what would be a good balance here?

**Comment by SethTisue** [comment]
I don't remember exactly how it looked before, tbh. Maybe it was overkill before and we can find a balance, or maybe I actually am contradicting myself, I'm not sure.

I do see we have the current version numbers at the bottom of https://scala-lang.org/download/

https://www.scala-sbt.org and https://www.rust-lang.org have a version number on the front page, but they only have one version number to shoehorn in

maybe we could leave the 2.12 version off and just do latest 3 and latest 2; I see that https://scala-lang.org/download/ groups 2.12 with the other antiques
