### ISSUE TITLE
502 Bad gateway at https://index.scala-lang.org/

### ISSUE THREAD

**Issue by visortelle** [scala/scala-lang#1438]
<img width="215" alt="Screenshot 2022-11-20 at 4 59 17 PM" src="https://user-images.githubusercontent.com/9302460/202912270-20d06797-96e9-48f6-bc89-05c43b7babec.png">

Find a library button link: https://index.scala-lang.org/

<img width="839" alt="Screenshot 2022-11-20 at 4 59 01 PM" src="https://user-images.githubusercontent.com/9302460/202912250-ec9e473f-0f99-4271-baa6-3856ac28e43d.png">

**Comment by adpi2** [comment]
Thanks for opening this issue. It seems that the Scaladex server crashed, I am taking a look.

**Comment by adpi2** [comment]
Scaladex is back.
