### ISSUE TITLE
scala-lang.org and its sub-hosts are not accessible via VPN 

### ISSUE THREAD

**Issue by odd** [scala/scala-lang#1456]
`scala-lang.org` and its sub-hosts (i.e. `contributors.scala-lang.org`) are unreachable using both [Mullvad](https://mullvad.net) and [OVPN](https://ovpn.com) (both are Swedish VPN-providers). It seems that the target server (canonical name `icvm0035.epfl.ch` at `128.178.218.46`) is not accepting traffic from certain VPN-associated addresses.

**Comment by SethTisue** [comment]
@fsalvi any insight here?

note that @odd isn't the only person experiencing this. a second person asked about it on Discord, wrt Mullvad specifically

**Comment by fsalvi** [comment]
Hello,
The scala-lang websites are hosted at EPFL.
Unfortunately, EPFL decided a few months ago to block all connection attempts from AnonVPN services because they just get too many attacks from these networks.
So, for now, there are no solution except using a direct connection instead of VPN to access the scala-lang websites (or other EPFL hosted services).
I will ask them again if there's any plan to relax this rule.

**Comment by fsalvi** [comment]
And the answer is: not for now. Blocking anonVPN has reduced significantly the number of attacks and phishing attempts...

**Comment by odd** [comment]
Thanks @SethTisue and @fsalvi 
For me personally it is not a problem to disable VPN when I need to access scala-lang.org, but I fear that others might not be so fortunate.

**Comment by staffanu** [comment]
I'm in Sweden and apparently our ISP is blocked so at our office we cannot access scala-lang.org. A bit contrary to the intention of the rule, we use a VPN in order to access the site:)  So it seems the rule that blocks certain traffic doesn't always work as intended.

**Comment by fsalvi** [comment]
> I'm in Sweden and apparently our ISP is blocked so at our office we cannot access scala-lang.org. A bit contrary to the intention of the rule, we use a VPN in order to access the site:) So it seems the rule that blocks certain traffic doesn't always work as intended.

Could you give me the IP ranger of your ISP provider and the name of the VPN you are using ? I will investigate further...

**Comment by staffanu** [comment]
Hi our subnet is 151.236.202.0 - 151.236.202.255, but the provider might of course have more IP ranges. I'm using ExpressVPN and selecting some countries work, some don't (for example, Norway works).

**Comment by fsalvi** [comment]
Your ISP network should now be allowed. Could you check if you can access scala-lang.org without VPN?

**Comment by staffanu** [comment]
We can! :)  Thank you!

**Comment by ckipp01** [comment]
Just saw this on Discord this morning

> lol, I was on a US VPN for some reason and the official website didn't open for me at all

Just a reminder that this seems to still be consistently biting people when trying to access the site.

**Comment by kraktus** [comment]
Hello, I'm affected by this issue too.

This is very unfortunate for a language documentation which should be as open and accessible as possible.

**Comment by fsalvi** [comment]
We'll address this issue soon.

**Comment by vidalgpr** [comment]
Hi there! My colleagues and I are facing the same issue in the office in Brussels. Our WAN IP is 85.119.217.122
Thank you in advanced

**Comment by fsalvi** [comment]
Hello,
As a first step, I started to experimentally host outside of EPFL network the www.scala-lang.org and docs.scala-lang.org websites at these URLs:
https://www3.scala-lang.org
https://docs3.scala-lang.org
You may have a look...

**Comment by kraktus** [comment]
Works great for me

**Comment by vidalgpr** [comment]
also works great here!

**Comment by Arraying** [comment]
> Hello, As a first step, I started to experimentally host outside of EPFL network the [www.scala-lang.org](http://www.scala-lang.org) and docs.scala-lang.org websites at these URLs: https://www3.scala-lang.org https://docs3.scala-lang.org You may have a look...

This works well, thank you! I was wondering, are there also plans to host Scastie outside of EPFL?

**Comment by fsalvi** [comment]
I'm doing some tests with Cloudflare to have our servers behind their reverse proxy.
You can try that (alpha version !):
https://scastie.scala-lang.net

It may take some time to load the first time because it still includes elements from scala-lang.org domain

**Comment by london-coder** [comment]
I have experienced the same issue. And it is REALLY annoying. Using NordVPN, connected to UK server(s), and I am in the UK, The scala-lang.org site is unreachable. So either I do not use VPN, and threaten my on-line security, or cannot access the Scala site. Scala seems to be dying a slow decline anyway, so it may not matter for much longer.....

**Comment by Arraying** [comment]
> I have experienced the same issue. And it is REALLY annoying. Using NordVPN, connected to UK server(s), and I am in the UK, The scala-lang.org site is unreachable. So either I do not use VPN, and threaten my on-line security, or cannot access the Scala site. Scala seems to be dying a slow decline anyway, so it may not matter for much longer..... BTW the www3.scala../www3.docs... does not work with VPN connection either.

Which NordVPN server (they all have numbers I believe) are you using? I'll see if I can replicate. No "luck" so far, I've tried London, Berlin and Amsterdam servers and they all seem to load the above websites (albeit slowly). Same with www3 links.

**Comment by london-coder** [comment]
Hi @Arraying, thanks for your response. I tried using 6 distinct servers that Nordvpn use. All of them were unable to connect to the scala-lang.org web site. I think that this is accounted for by the previous explanation that EPFL took the action to block VPN servers. As, by connecting to a US (NordVPN) server, allowed me to reach the scala-lang.org site while still being connected to the VPN.
Hi @fsalvi, Thank you for your response. You are right. It turned out I had accidentally added a 'space' character while trying the www3.scala-lang.org (and www.scala-lang.net), do indeed work while using a VPN connection. Thank you again, for your input :-)

**Comment by bjornregnell** [comment]
Today I hit this issue when surfing on the WLAN offered by the Swedish national train service... Perhaps the official pages should be hosted by another method that can allow vpn access?

**Comment by SethTisue** [comment]
I've submitted a draft proposal to the Scala Center on this subject, here: https://github.com/scalacenter/advisoryboard/pull/132

**Comment by fsalvi** [comment]
Now all websites are behind Cloudflare:

* main websites
- https://www.scala-lang.org
- https://docs.scala-lang.org

* web applications
- https://index.scala-lang.org
- https://scastie.scala-lang.org

* discourse forums
- https://users.scala-lang.org
- https://contributors.scala-lang.org

So, they should be accessible without any problem with any VPN.

**Comment by SethTisue** [comment]
@julienrf I think this merits a short blog post, wdyt?

**Comment by julienrf** [comment]
Yeah, good idea: https://github.com/scala/scala-lang/pull/1522
