### ISSUE TITLE
"Scala in a Nutshell" header isn't centered like the others (depending on zoom level)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1468]
see image

@bishabosha I poked a bit at trying to fix this but I don't know what's going on and I don't actually know CSS, maybe you can spot the problem?

<img width="678" alt="before" src="https://user-images.githubusercontent.com/161079/217987119-e37e1bc6-f46e-49e2-a096-61201cfa93e2.png">

**Comment by SethTisue** [comment]
gah, I realized I should check other browsers, and it's only broken in Safari, Firefox and Chrome are fine 🙀

**Comment by bishabosha** [comment]
I use safari and don't see this, did you empty the caches?

**Comment by SethTisue** [comment]
Turns out I had Safari set to display at 125% zoom; the problem goes away at 100% zoom.

Does that enable you to reproduce it?

**Comment by bishabosha** [comment]
oh yes in that case I can reproduce it when I zoom in

**Comment by bishabosha** [comment]
it appears that there is not enough padding so when the "API Docs" and "Migrate to Scala 3" labels go on 2 lines it pushes the title to the right :)

**Comment by bishabosha** [comment]
The page layout has changed since this issue was opened - so the issue doesn't appear anymore, nor anything similar when zooming
