### ISSUE TITLE
scala-lang.org and docs.scala-lang.org are down

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1471]
as reported by users on Discord and verified with https://downforeveryoneorjustme.com

@fsalvi ...?

**Comment by polkovnikov-ph** [comment]
Same here.

**Comment by fsalvi** [comment]
EPFL has some problems with the platform hosting the VMs. I'm working on it...

**Comment by Adam-Vandervorst** [comment]
Are there backup sites or mirrors that host the docs and language overview etc.?
If not, we may want to resolve the single point of failure, regardless of this incident.

**Comment by eed3si9n** [comment]
Works for me (2023-02-22 16:42Z).

**Comment by SethTisue** [comment]
up again for me as well
