### ISSUE TITLE
Proposal - Main Page - Unneeded

### ISSUE THREAD

**Issue by diesalbla** [scala/scala-lang#1495]
The main page of the website https://scala-lang.org/ has a section like the following

________________
#### Looking for upcoming events?

Or want to chat with like-minded users? Visit the [Community page](https://scala-lang.org/community/) to learn more.
______

Given that the link to the "Community" already appears at the top of the page, this section seems unnecessary and may be cut off.

**Comment by bishabosha** [comment]
Originally I left that section there for visitors used to the old design, who may be confused that the events moved to the community page - maybe it has been long enough?
