### ISSUE TITLE
Proposal - No All versions

### ISSUE THREAD

**Issue by diesalbla** [scala/scala-lang#1496]
**Situation** The main page https://www.scala-lang.org/ offers three buttons for downloads, marked as "Scala 3.2.2", "Scala 2.13.10", and "All Releases" 

**Assumption 1** Most people downloading Scala from the web-page may be well served with the latest version.
**Assumption 2** The webpage should encourage use of latest versions. Even https://www.python.org/, known for a bumpy major version transition, only links to latest version. 

**Proposal** Remove link to "All Releases" version.

**Comment by eed3si9n** [comment]
Any Python code I've encountered at work in the last few years have been all Python 3.x, and the discussion was more about which minor version of 3.x to use.

Scala on the other hand, any Scala code I've encountered at work in the last few years have been Scala 2.11 and 2.12, and the discussion was about which minor version of 2.x to migrate up to. Consequently, 9 out of 10 times when I visit https://www.scala-lang.org/ is to find out the current latest version of Scala 2.11 and 2.12, and I personally appreciate the All Releases button.

**Comment by bishabosha** [comment]
For some background, until I merged https://github.com/scala/scala-lang/pull/1435, there seemed to be significant calls to put version numbers back on the home page, and there was praise after it was merged.

**Comment by som-snytt** [comment]
I used to use the All Releases link exclusively.

To me, the buttons in question say to the newcomer, "Show me the web page for this version," not "download." It's nice to advertise the current versions, though, irrespective of the buttons.

But I also like a quick link to the downloads (as an experienced user who knows what I want).

I'd prefer a DOWNLOAD link at top header for current "all" page, and remove INSTALL, with the Coursier text confined to "Getting Started". (IIRC it used to be DOWNLOAD at top.) The "Getting Started" seems to me right place to explain how and what to install, but it's a complicated page. As an experienced user, it defeats me.

**Comment by julienrf** [comment]
I also think we should keep the link to “All Releases” for now. I am closing this issue but feel free to continue the discussion in the comments and we may re-open it.
