### ISSUE TITLE
update sdk install instructions to include the actual version

### ISSUE THREAD

**Issue by bjornregnell** [scala/scala-lang#1560]
On this page https://www.scala-lang.org/download/3.3.1.html
it says: `sdk install scala`

But I need to do
```
sdk install scala 3.3.1
sdk default scala 3.3.1
```
if I don't have a fresh install, but already have e.g. 3.3.0 installed.

If I do like in the instructions it for some reason downloads very old 3.1.1 and ask me to set that as default even if I also have 3.3.0 installed as (previous) default.

I'm not sure how sdkman thinks about the latest version of scala and the only safe thing to really get the actual version is to state it explicitly, hence I think the download page for each new version should also add the specific version after `sdk install scala`.

**Comment by bjornregnell** [comment]
Sometimes `sdk install scala 3.3.1` asks me if it should be the default but not always. I'm unsure exactly when `sdk default scala 3.3.1` is needed after install. But it does not hurt to include it in the instructions.

**Comment by bishabosha** [comment]
> I'm not sure if it is the same issue with brew, but it seems to me natural that explicit version is given also to brew.

brew doesnt really support versioning, you have to manually create a new formula for each "older" version, with scala so far they are only done by major version, so `scala@2.13`

**Comment by hamzaremmal** [comment]
> > I'm not sure if it is the same issue with brew, but it seems to me natural that explicit version is given also to brew.
> 
> brew doesnt really support versioning, you have to manually create a new formula for each "older" version, with Scala so far they are only done by major version, so `scala`, `scala@2.13`, `scala@2.12` etc

I've added [scala@3.3](https://github.com/Homebrew/homebrew-core/pull/164834) to homebrew last weekend. We now have all the formulas in the core tap :-)
