### ISSUE TITLE
`api/current` points to Scala 2 stdlib Scaladoc, should point to Scala 3

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#1579]
https://www.scala-lang.org/api/current/ still links to Scala 2

https://www.scala-lang.org/api/3.x/ is the Scala 3 link

I suggest we introduce a https://www.scala-lang.org/api/2.x/ link and then have https://www.scala-lang.org/api/current/ redirect to https://www.scala-lang.org/api/3.x/ , something like that?

a newcomer on Discord was bitten by this today. they logically assumed from the URL that they must be looking at the latest. (true, they failed to notice the "2.13.12", but we have a lot of publicity saying that Scala 3 just uses the Scala 2 standard library, and that's true most of the time, but it isn't true for certain things that Scala 3 added or changed, such as tuples... but these are subtleties we can't assume people know)

@fsalvi I think this might be in your wheelhouse?

**Comment by fsalvi** [comment]
Sure. I modified the links accordingly.

**Comment by SethTisue** [comment]
I may need to be careful at 2.13.13 release time that I don't overwrite this. I'll make a note to check on it and update our release steps if necessary.
