### ISSUE TITLE
Add binary compatibility guide 

### ISSUE THREAD

**Issue by gkossakowski** [scala/scala-lang#16]
Provide a guide that covers:
- history of binary compatibility in Scala so we can show that our policy evolves in the right direction
- define binary compatibility (there different concerns like serialization, linkage errors, etc.)
- present tradeoffs we face when it comes to binary compatibility
- describe current policy in 2.10.x series
- mention tools we use (mima) which is related to hackers guide

**Comment by SethTisue** [comment]
http://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html

**Comment by lrytz** [comment]
We should still have a binary compatibility guide for authors, explaining what kind of changes are binary compatible. The page above only explains the policy of the Scala library. Should I open a separate issue for that?

**Comment by SethTisue** [comment]
@lrytz sure

**Comment by SethTisue** [comment]
but in https://github.com/scala/scala.github.com I think

**Comment by lrytz** [comment]
ok, https://github.com/scala/scala.github.com/issues/621
