### ISSUE TITLE
Create a page for Scala IDEs

### ISSUE THREAD

**Issue by makingthematrix** [scala/scala-lang#1657]
There is a page for libraries and tools (https://www.scala-lang.org/community/index.html#community-libraries-and-tools) and I know that an IDE is technically a tool, but:
1. No IDE is mentioned there
2. IDEs are central to the software development so much that I believe they deserve a separate page

Basically, we have two main Scala IDEs: IntelliJ Scala Plugin, and VS Code with Metals. There are others and I think it would be nice to mention them as well, but we can start with these two. Creating a separate page for them, and linking it from the main page, would add credibility in the eyes of newcomers: you consider learning a new programming language, you go to its website, and you see that two main IDEs in the programming world support that language. Cool. You already feel more confident that you made a good choice. 

The page could be simple, for start. Just the titles, links to the landing pages of both IntelliJ Scala Plugin and VS Code Metals, screenshots, and descriptions written in collaboration with both teams. 

Besides, right now, if you go to Google Search and ask for "Scala IDE", the first result you get will be "Scala IDE for Eclipse" which is discontinued for many years. This is a bad look. IntelliJ Scala Plugin already positions itself as "Scala IDE" on its landing page in order to go higher on the Google list. An external link to our landing page from scala-lang.org would help a lot. 

PS. I already worked on the "Scala on Android" article, so I can create the page myself if I get a green light.

**Comment by bishabosha** [comment]
Thank you for the suggestion, this would be a great addition. Particularly also would be good to revamp the Getting Started guide with better information on IDE

**Comment by MateuszKubuszok** [comment]
IMHE (mostly with StackOverflow) it would be nice to address 2 things:

 * Scala IDE (the old one, based on Eclipse) - there are still people stuck on old versions of Scala - not supported by Metals - who are stuck on Scala IDE and would have to get the information what they can do do make their IDE work (specific Eclipse and JDK versions, updated links, etc). It's not a priority for a newcomers but if we want to be supportive of all users we might have a dedicated section for these folks
 * I saw some people were very keen on using Scala IDE even when they could migrate _because they believed Metals and IntelliJ to NOT be a FOSS_ - so it might be worth highlighting that IntelliJ Community Edition + Scala are FOSS (I saw some CTOs who were sure that IJ has only paid edition, and they were considering some moves, e.g. away from Scala, just based on this assumption which at the time was untrue for several years), and that one can use Metals with many FOSS editors (if you do not consider VSCode to be one, there is VSCodioum, Vim, Emacs, etc)

These might have lower priority than just initial page with "getting started" but it might be valuable to have them at some point to prevent FUD.

**Comment by tgodzik** [comment]
Late to the party but:

> there are still people stuck on old versions of Scala - not supported by Metals -

I could try to back publish versions for some older Scala versions, Do you know which ones people might be stuck on?

**Comment by MateuszKubuszok** [comment]
I'd have to look up the questions on StackOverflow, but apparently there are people stuck maintaining old Spark versions on 2.9/2.10 (maybe a few even earlier). I saw some mention about people who managed to _finally migrate on Scala 2.11_. I imagine such teams are virtually without an IDE making any attempt to migrate even harder.

**Comment by tgodzik** [comment]
Och, I tried publish for older, but we are missing a bunch of things there :/

**Comment by SethTisue** [comment]
I'm in favor. Gonna go look at the PR now.

**Comment by SethTisue** [comment]
> there are still people stuck on old versions of Scala

As a matter of policy, we don't document anything older than 2.12 on the main site. At most, we could include a short link to information hosted elsewhere.

**Comment by SethTisue** [comment]
scala/docs.scala-lang#3042 is merged, new page is live at https://docs.scala-lang.org/getting-started/scala-ides.html, thank you @makingthematrix !
