### ISSUE TITLE
scala.js snippet on frontpage is broken

### ISSUE THREAD

**Issue by OlegYch** [scala/scala-lang#1667]
running https://scastie.scala-lang.org/gyNudjdITL2irc9ni0kRxA fails with
```
org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.16 (supported up to: 1.13): /home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.16.0/scalajs-library_2.13-1.16.0.jar:/scala/scalajs/LinkingInfo.sjsir
You may need to upgrade the Scala.js sbt plugin to version 1.16 or later.
```

**Comment by sjrd** [comment]
@rochala Looks like Scastie needs to bump its Scala.js version to 1.16.0. Are you still in charge of Scastie?

**Comment by rochala** [comment]
> Are you still in charge of Scastie?

I'm still trying to maintain it. I'll redeploy it today

**Comment by OlegYch** [comment]
@sjrd i think it's a matter of creating a new snippet and updating the link

**Comment by rochala** [comment]
It seems that Scala.js is already at 1.16, @OlegYch is right. It seems like changing a versions doesn't update Scala.js plugin version in configuration so there is a bug indeed. To update sbt plugin version you need to switch target to e.g jvm and then back to JS

This is the new link working on latest LTS with latest library versions.
https://scastie.scala-lang.org/CQ70LFpbRJuWEDfGxbuYeQ

**Comment by sjrd** [comment]
Thanks for the link! PR to include it at #1668.

**Comment by rochala** [comment]
The long term solution for this, would be adding a support for github organisations to login to Scastie, and then migrate all snippets there. We could then modify snippets, without the need for PR
