### ISSUE TITLE
news archive page does not updated

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-lang#197]
![2014-04-22 15 16 30](https://cloud.githubusercontent.com/assets/389787/2761923/ebaa639e-c9e5-11e3-9208-0691cbedd7a8.png)
![2014-04-22 15 16 42](https://cloud.githubusercontent.com/assets/389787/2761924/ebb0c9c8-c9e5-11e3-871e-c341fd0bc750.png)

http://scala-lang.org/news/
https://github.com/scala/scala-lang/tree/master/news/_posts

**Comment by adriaanm** [comment]
+1 https://www.dropbox.com/s/k8b2ldfouroqo6z/Screenshot%202015-02-09%2021.59.09.png?dl=0

**Comment by SethTisue** [comment]
only the items with a `post-type` of `news` are appearing; the missing ones all have `post-type` of `announcement`

I don't understand the intent behind the distinction. perhaps @heathermiller can clarify?

**Comment by SethTisue** [comment]
in `news/index.md`, is there any reason not to change `{% if p.post-type == 'news' %}` to allow the `announcement` case also?

**Comment by heathermiller** [comment]
Announcements are noisy. If there are M news posts and K announcements, typically M << K. So a news page would be essentially a change log peppered with a news announcement every 6 months. That was the intention.

Instead it'd likely be more intelligent to have an index of announcements and an index of blog + news articles. That makes more sense than the current set up, I think.

**Comment by SethTisue** [comment]
I understand better now... I'll think on this.

FYI @dickwall (iirc you were puzzled by this as well)

**Comment by heathermiller** [comment]
Why don't we just put items with `post-type` `news` and `blog` and rename it "archive" rather than "news archive"? Then the list of items shown is a bit more sensible. 

We can also change `announcement` post-types to `release-announcement` perhaps and have an "Release Announcement Archive" as another index of pages.

**Comment by SethTisue** [comment]
I would like to do something about this, but I can't really do surgery on the site if I can't preview stuff locally, so it's blocked by #361

**Comment by heathermiller** [comment]
I don't understand what your problem is. This complaint isn't descriptive enough. I use Jekyll versions 1-3 across computers to build locally without issue. What does "i can't preview locally" mean? What kind of errors are you getting that's preventing you from using Jekyll locally?

**Comment by SethTisue** [comment]
re: Jekyll, I've responded at #361

**Comment by SethTisue** [comment]
The changes you propose [above](https://github.com/scala/scala-lang/issues/197#issuecomment-156388460) SGTM.
