### ISSUE TITLE
API Doc filters don't display in Chrome

### ISSUE THREAD

**Issue by g-eorge** [scala/scala-lang#201]
Tested on OS X, Chrome 34

![screen shot 2014-05-01 at 13 04 46](https://cloud.githubusercontent.com/assets/440006/2851981/04272778-d129-11e3-9ebd-348083765552.png)

**Comment by SethTisue** [comment]
if this is still an issue, could you report it at https://issues.scala-lang.org? sorry, it was natural for you to suppose this would be the right place. but although the API docs are hosted on scala-lang.org, they're generated by the Scaladoc tool, which is part of Scala itself, so we track issues with it in the main Scala bug tracker.
