### ISSUE TITLE
Docs reference old shebang style

### ISSUE THREAD

**Issue by mcandre** [scala/scala-lang#204]
The Scala docs describe an old style of shebangs, using multiple lines:

http://www.scala-lang.org/documentation/getting-started.html

    #!/bin/sh
    exec scala "$0" "$@"
    !#

The new style, working in 2.10, works like simple shebangs in other languages:

    #!/usr/bin/env scala

Could we please update the documentation to reflect this?

**Comment by dragos** [comment]
This was fixed at some point. closing.
