### ISSUE TITLE
Training feed broken

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#260]
Events appear in the feed, but when you click on one, you are brought to the URL: http://scala-lang.org/test which returns "Not found."

**Comment by sjrd** [comment]
Seems like that's we get from the Typesafe feed: http://scala-lang.org/resources/php/typesafe-feed-trainings.php
All `url` fields have `"test"` as value.

**Comment by sjrd** [comment]
It's like that at the source feed as well: http://www.typesafe.com/subscription/training.json
There's nothing we can do here. Typesafe must fix their JSON feed. Who's in charge of that thing, these days?

**Comment by heathermiller** [comment]
Thanks Séb. No idea – @rasummer do you know who's in charge of the JSON feeds being published by Typesafe? It seems visitors can't make it from scala-lang.org to typesafe.com's training pages.

**Comment by rasummer** [comment]
@heathermiller @sjrd I'll take a look and find out who maintains these.

**Comment by heathermiller** [comment]
Update on this. @rasummer fixed the URL in the typesafe feeds. However, something seems to still be broken on our end – all training URLs come back as "http://scala-lang.org/undefined". @sjrd could you take a look at this?
