### ISSUE TITLE
Contributor hall of fame is always outdated

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#274]
It makes us look bad to have something static sitting there always outdated.

@sjrd – what about setting up a monthly cron job that either commits and pushes or makes a PR to scala-lang?

I think we should find a way to keep it updated or remove it all together. It's otherwise acting as cruft.

**Comment by sjrd** [comment]
I thought @fsalvi had set up that cron job?

**Comment by sjrd** [comment]
But otherwise, I think we should just remove it.

**Comment by fsalvi** [comment]
I will fix it !

**Comment by gourlaysama** [comment]
Ping @fsalvi: it is still outdated (stuck in January) :-)

**Comment by fsalvi** [comment]
I thought it has been removed:
https://github.com/scala/scala-lang/pull/276

Isn't it ?

**Comment by gourlaysama** [comment]
It is still online at http://scala-lang.org/contribute/scala-fame.html, and still linked from [the contributing guide][1].

It seems like it was removed because it isn't updated, and isn't updated because it was going to be removed... /cc @dickwall 

[1]: http://scala-lang.org/contribute/guide.html#why_contribute_a_patch_to_scala

**Comment by fsalvi** [comment]
Ok ;-) It's fixed now.

**Comment by gourlaysama** [comment]
Awesome, thanks!

**Comment by fsalvi** [comment]
I got an error when trying to update it.
Any idea ?
Error:
Server returned HTTP response code: 400 for URL: https://github.com/scala/scala/graphs/contributors-data

**Comment by fsalvi** [comment]
I wrote to github support, here is their answer:

--------------
Hello Fabien,

Thanks for reaching out. The endpoints you are using are not official APIs (they're not documented on https://developer.github.com/v3/) -- they are used to power features of GitHub.com and you should not be relying on them working in a specific way or being there at all. They might be changed without notice or completely removed, and you should be aware of that.

Instead, you should be using the API to fetch this data:

https://developer.github.com/v3/repos/statistics/#contributors
---------------
