### ISSUE TITLE
Variadic Template (Generic Varargs) in Scala?

### ISSUE THREAD

**Issue by esdrasgit** [scala/scala-lang#297]
do You intend to implement the Variadic Template in Scala?
in this way, you eliminate 22 Tuple classes (Tuple2, Tuple3, ..., Tuple22) and other classes that has same problem like Function classes (Function0, ...)
I think it's a little ugly to see

**Comment by sjrd** [comment]
Hi,

For discussions about the design of the language (among other things), the appropriate channel is [the scala-debate mailing list](https://groups.google.com/forum/#!forum/scala-debate). I recommend you ask your question there.
