### ISSUE TITLE
Link Community wiki not opening

### ISSUE THREAD

**Issue by mmrath** [scala/scala-lang#325]
Community link in scala-lang.org is not opening.

Looks like the source is:
https://github.com/scala/scala-lang/blob/master/community/index.md

Can someone please fix it?

**Comment by sjrd** [comment]
Works well enough for me: https://wiki.scala-lang.org/display/SW/Welcome+to+the+Scala+Wiki!
Were you experiencing a transient error?

**Comment by SethTisue** [comment]
link to wiki was removed in #323, since wiki is moribund
