### ISSUE TITLE
Broken “community tickets” links on community page

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#331]
several of the links have rotted because of changes made in JIRA

reported by “Performant Data LLC” at https://groups.google.com/d/msg/scala-internals/NeNXeQtQQyU/1SLiRsvMAgAJ

**Comment by dickwall** [comment]
Fixed the filters by removing the invalid labels. Queries no longer fail. Leaving this open though as I need to do a bigger sweep through and tune the specialized queries to contain the correct components.

**Comment by SethTisue** [comment]
@dickwall still interested? if not, let's unassign you

**Comment by SethTisue** [comment]
now that we've moved Scala bugs off JIRA and onto GitHub Issues, this needs a fresh look

**Comment by Philippus** [comment]
fixed in https://github.com/scala/scala-lang/pull/828
