### ISSUE TITLE
ongoing: stuff that scala_lang should tweet

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#357]
@soc asked for a place people could suggest things for https://twitter.com/scala_lang to tweet or retweet. the tweets show up on the front page of scala-lang.org too, so putting the ticket for that here.

the most active hands in the Twitter puppet lately have been mine and @heathermiller's — probably some other people have access, not really sure.

we haven't actually established any guidelines for what gets tweeted. but I'm pretty sure we want to keep the volume low (definitely not more than 1 tweet/day? we've averaged more like 1/week actually) and only tweet stuff that's likely to be of interest to the entire community

@odersky often just tweets Scala news directly, we don't bother retweeting from @scala_lang.

anyway, suggestions taken here. if you want to discuss or debate, Gitter is a better place for that. not looking to have a lot of meta-discussion about this.

**Comment by soc** [comment]
Maybe we can just create a Google Docs document, so that people can add (and schedule tweets) for specific days?

**Comment by heathermiller** [comment]
I don't think a github issue for the website is an appropriate place to post suggestions on how to use the Twitter account. These are separate things. Likely a google doc or an email thread is a better place for this.

**Comment by heathermiller** [comment]
@soc why don't you create a Google doc and share it on the scala-internals mailing list for other people to add to?

**Comment by SethTisue** [comment]
sigh, it appears from my searches that Google documents have no mechanism for sending out email notifications when a document is updated, so we'd have to remember to go look at it? (but Google spreadsheets _do_ have that feature...)

**Comment by DarkDimius** [comment]
@SethTisue, if you configure access so that people do not edit google doc directly, but suggest changes instead, you _will_ get notifications.
