### ISSUE TITLE
Add the posting date to individual news posts

### ISSUE THREAD

**Issue by ebruchez** [scala/scala-lang#371]
The [archive link](http://scala-lang.org/news/) contains dates, but individual posts don't.

I had noticed this in the past already to my great frustration, but I use [Google Alert](https://www.google.com/alerts) to keep track of certain things and today I just got an alert or [Scala: Next Steps](http://www.scala-lang.org/news/roadmap-next/). Not great from Google's part, I know, but landing on that page without a post date makes it hard to figure out if it's current news or not. Anyway, I am not sure I need to make a case for dating documents ;)

**Comment by SethTisue** [comment]
thanks for reporting. I've noticed this as well. I'm interested in fixing it as soon as we can get https://github.com/scala/scala-lang/pull/373 through.

**Comment by ebruchez** [comment]
Excellent. This is the kind of things that will show that there is some love behind the site. (I am not sure how this plays with @soc's work on this.)

**Comment by ebruchez** [comment]
Perfect, I see the date in postings now.
