### ISSUE TITLE
Make layout responsive (again, again?)

### ISSUE THREAD

**Issue by ebruchez** [scala/scala-lang#372]
I see #19, but the layout is clearly not responsive now. The main Scala web site _must_ be readable on a smartphone.

**Comment by heathermiller** [comment]
This complaint could be a bit more helpful. Currently you tell us what we  _must_ be doing, which is of course not very constructive. What browser are you using? What do you want to see?

At the time that I designed the Scala website, there were no responsive-first CSS frameworks and many aspects of the current layout wouldn't fit into any currently popular responsive CSS framework. The Scala website was a (large) contribution that I made on the side as a student. Given that we have no dedicated web/design person any large overhauls to the design/layout of the website is quite out of scope. 

Although we would be happy to receive such a contribution!

**Comment by SethTisue** [comment]
@ebruchez I don't know very much about CSS or about responsive design, but... can you (or anyone else who happens to see this ticket) identify any modest changes we could make that would improve the situation?

**Comment by ebruchez** [comment]
Sorry @heathermiller not a criticism of your work, I thought this was an obvious one. Take Chrome dev tools and set it e.g. for an iPhone 6S Plus. You see this:

![iphone6plus](https://cloud.githubusercontent.com/assets/105769/11876892/c9ad0250-a4a0-11e5-9e39-c6f67ca19342.png)

What I expect on a mobile phone is (at least for the news part but ideally for the whole site):

- single-column layout
- larger, readable font

I can't look at this immediately so can't tell if it's easy or hard to just hack in a couple of CSS fixes to improve the experience.

**Comment by heathermiller** [comment]
It would require pretty significantly changing the layouts of all pages. One would have to rebase all pages on newer "responsive-first" CSS frameworks. Many aspects of the front and inner pages would have to change because they can't be easily translated to a 12-col "responsive" grid format as in frameworks like Bootstrap. So the way we do the sidebars on inner pages, and the way we display blog entries etc on the front page would all have to change.

As this requires non-trivial changes to the layout across the entire website, and since we have no one who can invest time in this, I have to mark this as out-of-scope.

So this will have to fall into the realm of "big contributions" if we would like to see it done.

**Comment by ebruchez** [comment]
I think that a full modern layout would be best, and I agree that would be a relatively big contribution. It might be possible to graft something purely in CSS, as @SethTisue suggests. Hard to know for sure without trying. I suggest keeping this open as ultimately it will have to be addressed.

**Comment by soc** [comment]
@ebruchez I have been working on this recently. The upgrades to the CSS framework certainly helped a bit, and in addition one gets quite far with CSS's media queries. It's not published yet, but the e.g. the frontpage looks a bit more usable:

Compare
http://i.imgur.com/WrBZgbK.png

with
http://i.imgur.com/oKdVPEi.png

**Comment by ebruchez** [comment]
@soc Great! I realize that I check more and more stuff on mobile even though I spend most of my day in front of a 30" monitor and I suspect it might be the case of more and more people.

The other day I noticed that the home page is unusable on a phone: you can't even scroll to see the content that overflows.

**Comment by SethTisue** [comment]
> I have been working on this recently

perhaps someone could look at the changes @soc made over at get-scala.org and see if any of it could be backported to this repo

**Comment by jarrodwb** [comment]
@SethTisue It looks like @soc took his site down and removed its history. It maybe possible to salvage some of the changes from forks that other people made of the site before it was destroyed.

**Comment by dwijnand** [comment]
https://github.com/scala/scala-lang/compare/master...f8d0e37815747e93cd53e2a9eec69e8cdd6d6067

**Comment by SethTisue** [comment]
interesting. but locally:

```
% git show f8d0e37815747e93cd53e2a9eec69e8cdd6d6067
fatal: bad object f8d0e37815747e93cd53e2a9eec69e8cdd6d6067
```

not sure how I would get that commit onto my machine. (and, might GitHub garbage collect it? where did you get that SHA?)

**Comment by jarrodwb** [comment]
I found a repo that is not to old. Maybe that helps. There may also be a more recent fork out there.

https://github.com/nightscape/scala-lang.git

**Comment by dwijnand** [comment]
When you create a PR against a repo in GitHub it creates a branch in the target repository with the changes in the PR. These branches are typically excluded when you clone or fetch from GitHub (but if you reference them you can fetch them).

So in this case I found this reasonably recent PR https://github.com/soc/scala-lang/pull/22 and used it's HEAD.

There might be a way to delete these branches from GitHub, but generally I don't think the commits they refer to will be garbage collected.

For ease of having these commit locally I've pushed a branch to my fork: https://github.com/dwijnand/scala-lang/tree/soc.

**Comment by SethTisue** [comment]
should be fixed by #606

**Comment by SethTisue** [comment]
#606 has been merged.

**Comment by ebruchez** [comment]
I can confirm that it is responsive now
