### ISSUE TITLE
Add links to Scala Center website in footer?

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#422]
/Doh, I didn't even think to do this. Thanks @deathmoves for suggesting :)

**Comment by SethTisue** [comment]
http://www.scala-lang.org/community/ also

**Comment by SethTisue** [comment]
did this happen in #606?

**Comment by Philippus** [comment]
this can be closed, was fixed in https://github.com/scala/scala-lang/pull/545 I think

**Comment by SethTisue** [comment]
thanks @Philippus for your attention to this and other tickets recently!
