### ISSUE TITLE
Add method declaration indentation to the Style Guide

### ISSUE THREAD

**Issue by dk14** [scala/scala-lang#427]
There is:

http://docs.scala-lang.org/style/declarations#methods (tells how to ident classes/traits/objects' declarations with a lot of parameters)

and:

http://docs.scala-lang.org/style/indentation.html (tells how to ident method call with a lot of parameters)

But none of it tells how to ident method declarations with multiple parameters...
Good example: https://github.com/paypal/scala-style-guide#parameter-lists

**Comment by lashchenko** [comment]
Another good example from [Databricks Scala Guide](https://github.com/databricks/scala-style-guide#spacing-and-indentation)
```scala
def newAPIHadoopFile[K, V, F <: NewInputFormat[K, V]](
    path: String,
    fClass: Class[F],
    kClass: Class[K],
    vClass: Class[V],
    conf: Configuration = hadoopConfiguration): RDD[(K, V)] = {
  // method body
}
```
I prefer this version because indents do not depend on the length of a method name.

**Comment by dk14** [comment]
I agree that it shouldn't depend on the methods name length, but I'd prefer two spaces ident because it might be hard to read when both name of method and param are in one "column".

**Comment by lashchenko** [comment]
For option with `2 spaces` parameters are not separated from method body. 
Also this is not single case of the method definition because method can be defined as `override`, `private` or `protected`.

**Comment by SethTisue** [comment]
I don't think sufficient consensus exists for the style guide to promote a single style here. I suppose it could offer options, or simply mention that styles vary.

**Comment by jarrodwb** [comment]
This issue is in the wrong repo. I think it should go on scala.github.com.

**Comment by SethTisue** [comment]
> This issue is in the wrong repo

agree. I invite anyone interested to open an issue there, or better yet, send a pull request
