### ISSUE TITLE
Scala hacker guide "Build" section is outdated

### ISSUE THREAD

**Issue by chaselal** [scala/scala-lang#437]
The [Build section of the Scala Hacker Guide](http://scala-lang.org/contribute/hacker-guide.html#build) provides instructions for building the scala repository. The Build section says to build with ant:

> The build tool is ant. If you are behind a HTTP proxy, include ANT_ARGS=-autoproxy in your environment.

and does not mention sbt at all. This appears to be outdated; the [Requirements section of the scala repository's README](https://github.com/scala/scala#requirements) says that the ant build is deprecated and that sbt should be used instead:

> You need the following tools:
> ...
> sbt, we recommend the sbt-extras runner script. It provides sensible default jvm options (stack and heap size).
> ...
> Apache Ant (version 1.9.3 or above) if you need to use the (deprecated) ant build.

Perhaps the Build section should include instructions for sbt, or simply reference the GitHub repository's Requirements section as the authoritative build instructions.

**Comment by heathermiller** [comment]
Hi @chaselal. Thanks for noticing this! We'd love a PR to address this issue – updating the Hacker Guide with the new instructions would probably be best if you've got a minute?

cc/ @retronym @lrytz @adriaanm (Scala team @ Lightbend, please don't forget that the Scala website includes sections like these when you are changing process... Would be great if you could make a PR to the website alongside of the README!)

**Comment by lrytz** [comment]
i think it would be better to link back to the README for information that is already there, instead of duplicating it.

**Comment by heathermiller** [comment]
@lrytz I disagree. By that rationale, we should then move the Hacker Guide to the README or delete it – just to ensure that information isn't duplicated (I'm sure that the build instructions aren't the only piece of information that's duplicate).

**Comment by lrytz** [comment]
I think the meat of the hacker guide is the detailed step-by-step process, which has a lot of value but would not fit into the readme. Note that there are already links to the readme and to the CONTRIBUTING.md in other parts of the guide.

That's just MO, if you prefer to keep it more self-contained that's also fine with me.

**Comment by chaselal** [comment]
Submitted a PR to get the updates rolling. I have just recently started working with the Scala repository, so a thorough update of the guide is outside my abilities right now.

**Comment by SethTisue** [comment]
the hacker guide could always use further improvements, but https://github.com/scala/scala-lang/pull/504 addressed the biggest problems, I think.
