### ISSUE TITLE
broken "Other resources" link on main download page

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#448]
from the top of scala-lang.org, the "Download" link leads to http://scala-lang.org/download/ . on the right of this page there is an "Other resources" link that leads nowhere.

as for why the link might exist at all, I'm guessing there's shared code that also generates pages such as http://scala-lang.org/download/2.11.8.html in which the link works because an "Other resources" section of the page does exist.

reported by E Merth and Oliver Ruebenacker at https://groups.google.com/forum/#!topic/scala-user/P9bdf-ulw6E

**Comment by adriaanm** [comment]
manually fixed for 2.12.0 with https://github.com/scala/scala-lang/commit/3f55787a6c51ed6f900c4a02f4c001e1c048d167

**Comment by jarrodwb** [comment]
I think this may have been fixed. If not than maybe the description of the issue should be reworded.
