### ISSUE TITLE
SI-9698 Remove ancient 2.11.0 nightly docs

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#453]
crufty docs dated 20140303 show up in Google search results, misleading innocent users

details at https://issues.scala-lang.org/browse/SI-9698. reported by @janekdb

**Comment by janekdb** [comment]
More crufty docs from simple query : `scala mutable buffer`

http://www.scala-lang.org/api/2.8.1/scala/collection/mutable/ArrayBuffer.html

![scaladoc-2 8 1](https://cloud.githubusercontent.com/assets/1123855/17665206/5cfbfbba-62f1-11e6-9b5e-af11289f73b8.png)

**Comment by DarkDimius** [comment]
If they are indeed indexed by search engines, instead of removing it would be nice to forward to new docs instead. This way docs would keep search ranking.

**Comment by SethTisue** [comment]
@fsalvi do you have an opinion on what the right path forward here might be?

for starters, I'd suggest that we de-index the docs for all Scala versions up to and including 2.10

but is there more we could do to encourage search engines to select the latest version?

**Comment by fsalvi** [comment]
We could a few things:
- a big cleanup in https://www.scala-lang.org/files/archive/ maybe mainly in nightly/ (let me know what to remove, I guess the "docs" directory which is 5 years old should not exist anymore)
- redirections
- de-index old docs from search engines

I suggest to start with the cleanup, but I need to know what to remove/rename/archive.
Thanks.

**Comment by fsalvi** [comment]
I removed the nightly/docs directory.

**Comment by SethTisue** [comment]
@fsalvi thanks for that – I hadn't meant to let this drop. We are still interested in improving the situation here.

I did a search for "scala mutable buffer" just now and the 2.9 docs were one of the top 3 results. could you exclude the docs for all versions older than 2.11 from being visible to search engines...?

**Comment by fsalvi** [comment]
Yes, I'll do that. But, do we need to keep these old files or not ? I have 40GB of api archives, I'm wondering if they are all useful...

**Comment by SethTisue** [comment]
can I see how that 40GB breaks down by pathname?

**Comment by fsalvi** [comment]
It's around 400 to 600 MB per version in api/ folder:
15      2.5.0
16      2.5.1
17      2.6.0
17      2.7.1
18      2.6.1
19      2.7.0
21      2.7.7
22      2.7.2
22      2.7.3
22      2.7.4
22      2.7.5
22      2.7.6
135     2.8.0
136     2.8.1
136     2.8.2
187     2.9.0
187     2.9.0.1
200     2.9.1
200     2.9.1-1
211     2.9.2
213     2.9.3
213     2.9.3-RC1
213     2.9.3-RC2
226     2.11.0-M7
274     2.11.0-M4
274     2.11.0-M5
297     2.11.0-M2
298     2.11.0-M3
313     2.11.0-M8
316     2.11.0-RC3
316     2.11.0-RC4
327     2.10.6
327     2.10.7
331     2.10.0
331     2.10.0-RC5
332     2.10.1
332     2.10.1-RC1
332     2.10.1-RC2
332     2.10.1-RC3
333     2.10.2
333     2.10.2-RC1
333     2.10.2-RC2
333     2.10.3
333     2.10.3-RC1
333     2.10.3-RC2
333     2.10.3-RC3
333     2.10.4
333     2.10.4-RC1
333     2.10.4-RC3
333     2.10.5
387     2.11.0
438     2.11.1
441     2.11.2
442     2.11.3
442     2.11.4
452     2.13.0-M4
477     2.12.0-M1
478     2.11.5
479     2.11.6
483     2.12.0-M2
483     2.12.0-M3
484     2.11.12
484     2.11.8
484     2.11.9
485     2.11.10
485     2.11.11
487     2.11.7
493     2.13.0-M5
545     2.13.0-RC1
546     2.13.0
546     2.13.0-RC3
547     2.13.0-M2
547     2.13.0-M3
547     2.13.0-RC2
547     2.13.1
552     2.13.0-M1
575     2.13.2
577     2.12.0
577     2.12.0-RC1
577     2.13.3
578     2.12.0-be43eb5
578     2.12.0-RC1-1e81a09
578     2.12.0-RC1-be43eb5
578     2.12.0-RC2
589     2.12.0-M4
592     2.12.0-M5
597     2.13.4
626     2.12.5
626     2.12.6
627     2.12.7
627     2.12.8
628     2.12.9
629     2.12.10
630     2.12.11
632     2.12.12
634     2.12.4
635     2.12.1
637     2.12.13
638     2.12.2
640     2.12.3
640     2.12.3-1
666     2.10.4-RC2
668     2.11.0-RC1
40195   total

**Comment by SethTisue** [comment]
@fsalvi I think it's fine to get rid of
* 2.5 through 2.9
* all milestones and RCs
* 2.10.0 through 2.10.6 (but keep 2.10.7)
* 2.11.0 through 2.11.11 (but keep 2.11.12)

**Comment by fsalvi** [comment]
I forgot about it: I did it a few days ago

**Comment by SethTisue** [comment]
thank you Fabien!
