### ISSUE TITLE
broken link to Scala release schedule page

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#459]
at http://www.scala-lang.org/news/, under the Announcements & Changelog section, there is an entry for @adriaanm's post last December, "2016 Scala Release Schedule update". but the link to http://www.scala-lang.org/news/2016-schedule is broken.

reported by Jason Webb at https://twitter.com/BigJasonWebb/status/766169748904157185

when I generate the site locally via `bundle exec jekyll serve`, the problem doesn't occur. something strange must be happening on the actual server. @fsalvi perhaps this is something you could look into...?

**Comment by SethTisue** [comment]
in the meantime, if anyone wants to see the page contents, they're at https://github.com/scala/scala-lang/blob/master/news/_posts/2015-12-09-schedule-update.md

**Comment by soc** [comment]
Maybe some Jeykll weirdness? Works for me: http://get-scala.org/news/2016-schedule

**Comment by matsluni** [comment]
I also could not reproduce it locally with jekyll. What worked for me though is: [http://scala-lang.org/news/2016-schedule**.html**](http://scala-lang.org/news/2016-schedule.html). So it seems to me that is related to front facing web server (e.g. nginx, apache, etc.)

After inspecting the response headers I found out that http://get-scala.org is served via Github (GH Pages?!) and http://scala-lang.org is served via apache. So maybe this is apache related?!

**Comment by fsalvi** [comment]
It's a problem with jekyll build, not with the web server. When specifying another permalink with a '.' inside the filename, it's ok.
We're using version 3.1.6 
I'll do some tests with the latest version to see if it solves the problem...

**Comment by fsalvi** [comment]
I did a quick fix.

**Comment by SethTisue** [comment]
thanks Fabien!
