### ISSUE TITLE
Erik Osheim receiving Phil Bagwell Award should be blog-posted

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#473]
as was done for Bill V last year at http://www.scala-lang.org/news/2015/06/25/bagwell-award-2015.html — that post could be used as a template

@propensive I imagine you're swamped right now, but let's not let this fall through the cracks, either

**Comment by propensive** [comment]
@SethTisue Agreed. Incidentally, on the subject of falling-through-cracks, I only clicked on this by chance, having been ignoring all GitHub email notifications over the last few weeks...

**Comment by SethTisue** [comment]
ping — might you have time for it this week?

**Comment by SethTisue** [comment]
@propensive ping

**Comment by SethTisue** [comment]
PR #503
