### ISSUE TITLE
2.12 spec should be available at http://www.scala-lang.org/files/archive/spec/2.12

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#479]
reported by Daniel Barclay at https://groups.google.com/d/msg/scala-user/kCjYrWV9KtI/tJFDrZxaEAAJ

* 2.11 URL: http://www.scala-lang.org/files/archive/spec/2.11/
* 2.12 URL: http://www.scala-lang.org/files/archive/spec/2.12/

**Comment by adriaanm** [comment]
The issue is in the last line of https://github.com/scala/scala/blob/2.12.0/.travis.yml
Will likely need to create the 2.12 dir first

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/5437

**Comment by SethTisue** [comment]
> Will likely need to create the 2.12 dir first

done. (ssh'ed to jenkins-worker-ubuntu-publish and from there to chara, then `mkdir`)

**Comment by SethTisue** [comment]
followup PR: https://github.com/scala/scala/pull/5438

**Comment by SethTisue** [comment]
dammit. so the second PR was good/needed, but also didn't fix the problem. now we've got a 2.12 spec, that identifies itself as such, at http://www.scala-lang.org/files/archive/spec/2.11/

I'll poke around https://scala-webapps.epfl.ch/jenkins/view/All/job/production_scala-lang.org-scala-dist-archive-sync/

**Comment by SethTisue** [comment]
Adriaan's working on providing Travis with an additional private key where the ssh forced command has `2.12` instead of `2.11`
