### ISSUE TITLE
bring Jekyll version in line with actual versions on server

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#498]
in [this comment](https://github.com/scala/scala-lang/pull/443#issuecomment-254430527) @fsalvi says that the server hosting scala-lang.org is running

```
$ jekyll -v
jekyll 3.1.6
$ kramdown -v
1.11.1
```

but our Gemfile has

```
gem 'jekyll', '1.5.1'
gem 'kramdown', '1.8.0'
```

we should bring these versions in alignment with each other

the short term fix would be to update the Gemfile. (we might need to ask @fsalvi for versions on the other gems listed there.)

a longer term fix would be for the server to generate the site using `bundle` rather than systemwide gems

an abandoned previous attempt to fix, with discussion: https://github.com/scala/scala-lang/pull/443

**Comment by Blaisorblade** [comment]
Question I'm wondering about: wasn't there (in #443) discussion of dialect differences between Jekyll 1.5 and Jekyll 3, associated Kramdown versions, and GFM dialect variants? Is the current output consistent with the later Kramdown version?

**Comment by fsalvi** [comment]
Versions we have on the server right now:

*** LOCAL GEMS ***
afm (0.2.2)
Ascii85 (1.0.2)
bigdecimal (1.2.8)
blankslate (3.1.3)
bundler (1.13.6)
classifier-reborn (2.0.4)
coderay (1.1.1)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
colorator (0.1)
did_you_mean (1.0.0)
execjs (2.6.0)
fast-stemmer (1.0.2)
ffi (1.9.10)
hashery (2.1.1)
io-console (0.4.5)
jekyll (3.1.6)
jekyll-coffeescript (1.0.1)
jekyll-feed (0.3.1)
jekyll-gist (1.1.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.3.0)
jekyll-watch (1.3.0)
json (1.8.3)
kramdown (1.11.1, 1.10.0)
liquid (3.0.6)
listen (3.0.3)
mercenary (0.3.5)
mime-types (2.6.1)
minitest (5.8.4)
multi_json (1.11.2)
mysql (2.9.1)
net-telnet (0.1.1)
oj (2.12.10)
parslet (1.7.1)
pdf-core (0.5.1)
pdf-reader (1.4.0)
pg (0.18.4)
posix-spawn (0.3.11)
power_assert (0.2.7)
prawn (2.0.2)
prawn-table (0.2.1)
psych (2.0.17)
pygments.rb (0.6.3)
rake (10.5.0)
rb-inotify (0.9.7)
rdiscount (2.1.8)
rdoc (4.2.1)
redcarpet (3.3.4)
rouge (1.10.1)
ruby-rc4 (0.1.5)
safe_yaml (1.0.4)
sass (3.4.21)
sequel (4.32.0)
sequel_pg (1.6.14)
stringex (2.5.2)
test-unit (3.1.7)
toml (0.1.2)
ttfunk (1.4.0)
yajl-ruby (1.2.0)

**Comment by fsalvi** [comment]
The build is now fine with bundler.
