### ISSUE TITLE
Scale up font contrast

### ISSUE THREAD

**Issue by charafau** [scala/scala-lang#509]
From [Hacker news discussion](https://news.ycombinator.com/item?id=12863579) someone mention font color readability. 

> Great stuff but can you please scale up font contrast a bit?
> Just removing this `body { color: #586E75 }` altogether makes your page readable.

I personally think that it's good idea. Screenshots for reference.

Now:

<img width="728" alt="screen shot 2016-11-04 at 16 12 22" src="https://cloud.githubusercontent.com/assets/1143994/19997422/c41357f6-a2a9-11e6-93dd-63d93e6e6ebd.png">

After change:

<img width="699" alt="screen shot 2016-11-04 at 16 12 30" src="https://cloud.githubusercontent.com/assets/1143994/19997428/cc93f6b0-a2a9-11e6-823b-e4f1e7b17c52.png">

**Comment by SethTisue** [comment]
LGTM — would you like to make a PR?

**Comment by SethTisue** [comment]
the corresponding issue in the docs site repo is https://github.com/scala/scala.github.com/issues/569

**Comment by SethTisue** [comment]
I'm not sure if this got addressed in #606 or not

**Comment by heathermiller** [comment]
Fixed in #606
