### ISSUE TITLE
regression: Twitter section on front page is empty

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#518]
I assume we're using some ancient API that doesn't work anymore?

a very old related issue: https://github.com/scala/scala-lang/issues/100

**Comment by jarrodwb** [comment]
This bug may actually be an improvement. ;-)

**Comment by jarrodwb** [comment]
What do people think about removing this section from the front page? I have been playing around with the idea locally and I like it. People can still find the Twitter account in the header.

**Comment by SethTisue** [comment]
I lean, mildly, towards keeping it. For better or worse, Twitter is our main way of getting news out.
