### ISSUE TITLE
Events page should show past events too

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#519]
requested by a user at https://gitter.im/scala/scala?at=5821fcb16cb72076304fcbd8

> I see we have an "upcoming events" page on the Scala website. Is there some place that keeps track of past events? I'm a bit out of the loop and I thought there was an event last week that might've uploaded talk videos.

one really easy way of addressing this would just be to include a link to the relevant directory in the git repo. ugly, but probably a one-liner

a better solution would be to actually show the events, after a break.

**Comment by jarrodwb** [comment]
There is a filter in the main.js file that controls what is displayed. I don't have much experience with javascript but I may get around to it at some point.

I am half tempted to redo the whole thing and use Jekyll, [datafiles](http://jekyllrb.com/docs/datafiles/) and Liquid. I don't think we need javascript to process these events and trainings. There is also some strange php files hanging out in the resources directory.

**Comment by sjrd** [comment]
The reason we did it in JS rather than server-side is so that it would update without needing to rebuild the static pages (which only happens when we push a new commit).

**Comment by SethTisue** [comment]
@propensive this might interest your reflective, looking-backwards side. you'll want to tackle it before writing your memoirs, surely

**Comment by SethTisue** [comment]
This came up today on scala/center Gitter. Someone wanted to know if there were any Scala conferences in Asia. Since the page doesn't show past events, we couldn't easily answer.

**Comment by propensive** [comment]
@SethTisue Heh, I just saw your comment from March, back when I was much worse at checking my GitHub notifications... The answer is "Scala Matsuri", but I had to rely on my memory rather than memoirs for that, and it is (to the best of my knowledge) the only Scala-only conference (series) that's been run anywhere in Asia. There have been some FP conferences in India too, I believe.

**Comment by lucianenache** [comment]
Hi, I would like to add this enhancement to the scala-lang page during the spree in Copenhagen on Wednesday.

There are a few ways we could get this done:

- Link to the github _posts in the events directory (ugly but quick)
- Create sub pages in the events page for Current and Past Events (we would filter them with jQuery - prefered)
- Create sub pages for each event stored in github where most recent is displayed on top page and on the sub-page a list pf past events and additional information can be displayed (too much work)


If you can point me out on which route to go, I could start looking into the code and get accustomed with it by Wednesday.

**Comment by SethTisue** [comment]
I agree that #3 is overkill. #2 seems nicest, but certainly #1 is much better than nothing and would count as success. See you tomorrow!

**Comment by SethTisue** [comment]
resolved by #658
