### ISSUE TITLE
We need a dev Scala version in _config.yml

### ISSUE THREAD

**Issue by jarrodwb** [scala/scala-lang#532]
713e699c8cfd2e454f25fb0595555788b36c703d introduced a bug that breaks the Development Release link in the footer of all the pages.

We need a value for `devscalaversion` that points to an actual page. The current rendering gives a link of `http://www.scala-lang.org/download/.html`.

**Comment by SethTisue** [comment]
hmm. not clear how to fix until 2.13.0-M1 comes out, which won't be for a while (a few months at least).

I really don't think we need to make the development version _that_ easy to find, so I'd be fine with a PR that simply removed devscalaversion and removed the link from the footer.

**Comment by SethTisue** [comment]
fixed (in a better way) by #539
