### ISSUE TITLE
automate broken link checking?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#535]
this could be part of the Travis build, using html-proofer or something like it

see #533, #534

**Comment by jarrodwb** [comment]
I think that all the broken links that have been found should be fixed before any major work on this is done. Every Travis build will fail unless the links are fixed first. #532 also produces a broken link on every page that has a footer.

**Comment by SethTisue** [comment]
I was able to run htmlproofer myself by adding this to `Gemfile`:

```
gem 'html-proofer'
```

then running `bundle install` and `bundle exec htmlproofer`

**Comment by SethTisue** [comment]
> Every Travis build will fail unless the links are fixed first

Idea: we could start by whitelisting existing broken links, to keep Travis green. That would prevent new PRs from making the situation worse. Then over time, we could try to shrink that list.

**Comment by SethTisue** [comment]
@OlivierBlanvillain any chance I could interest you in porting https://github.com/scala/docs.scala-lang/pull/947 to this repo...?

**Comment by SethTisue** [comment]
@OliverBlanvillain @Phillippus or anyone else watching this repo interested in tackling this...? it's super high value. Olivier has already done most of the heavy lifting on setting up htmlproofer, and @Phillippus has already done most of the work of fixing broken links.

**Comment by jarrodwb** [comment]
It's been a while since I looked into this Repo. Luckily I have a little time today to get back up to speed.

I will let you know what I find. 🙂

**Comment by OlivierBlanvillain** [comment]
I won't have time to finish it, but here is a work in progress branch if someone wants to pick it up:

https://github.com/OlivierBlanvillain/scala-lang/commits/cleanup-links

The message in the latest commit shows that they are currently 320 broken links according to htmlproofer.

**Comment by Philippus** [comment]
check out https://github.com/scala/scala-lang/pull/838
`bundle exec htmlproofer ./_site/ --only-4xx --empty-alt-ignore --allow-hash-href --url-ignore "/files/,/api/,https://github.com/username"` now gives just a few broken links.

**Comment by OlivierBlanvillain** [comment]
Nice! Still, I think there is no reason to have broken links to `/files/` and `/api/`. After fixing a few obvious ones I'm at 66 failures on the branch linked above.

**Comment by Philippus** [comment]
to me it looks like you're not working from the most recent master branch though...

**Comment by OlivierBlanvillain** [comment]
Indeed, I messed up my rebase somehow... @Philippus Thanks for doing most of the hard work! PR with zero broken links: #840

**Comment by SethTisue** [comment]
🎉
