### ISSUE TITLE
push sbt more for getting-started...?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#536]
since #530 the download page suggests sbt as a getting-started option, but http://www.scala-lang.org/documentation/getting-started.html still doesn't

other popular getting-started resources such as https://gist.github.com/djspiewak/cb72c41ac335a3a9b28b3307be04aa43 and https://tpolecat.github.io/2014/12/12/getting-started.html are unequivocal about suggesting sbt

I don't know what the right way to handle this is, but for the page not to even mention or acknowledge sbt isn't the right solution IMO.

**Comment by SethTisue** [comment]
Corresponding to the getting-started options offered on the download page, one could imagine three or more getting-started pages with similar content: one for the command-line compiler option, one for sbt, and one or more IDE-based ones. (Maintaining them in parallel would be a bit of a pain.)

**Comment by ashawley** [comment]
This is the existing page for the "command-line compiler option"

http://www.scala-lang.org/download/install.html

**Comment by SethTisue** [comment]
I gather work on this is currently happening at the Scala Center.

**Comment by heathermiller** [comment]
Yep, @travis032654 has been working on getting started documentation. I think he'll make a PR sometime soon with the new docs he's written (thoroughly reviewed already by everyone at the Scala Center, but not yet by the community)

**Comment by travis032654** [comment]
They don't really fit into the current structure of the docs site. We're working on restructuring that as well. Hopefully the designs from 47 Degrees will come through in the next week and I can create pull requests for the tutorials.

**Comment by heathermiller** [comment]
@travis032654, this ticket relates to scala-lang.org, not the doc site. (The doc site is in repo scala.github.com). And I think Seth was referring to the getting started guide that you overhauled, so this would be the stuff we'd link to from the download page.

**Comment by travis032654** [comment]
Okay, I'll create a PR.

**Comment by SethTisue** [comment]
this is in progress at https://github.com/scala/scala-lang/pull/608

**Comment by SethTisue** [comment]
mission accomplished
