### ISSUE TITLE
tweets section is way too big

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#548]
can we control the appearance of this? I don't remember what it looked like before, since it's been broken for some time, but how it looks now — well, “prominent” is the nice way @jarrodwb put it, I was thinking more along the lines of "gigantic and hideous" :-)

**Comment by jarrodwb** [comment]
;-)

Its current form is better than nothing. I am sure we can get it fixed up in a day or two.

**Comment by SethTisue** [comment]
<img width="537" alt="screen shot 2016-11-21 at 1 09 50 pm" src="https://cloud.githubusercontent.com/assets/161079/20500801/d3e31726-afeb-11e6-88c6-a0aac85483ae.png">

**Comment by jarrodwb** [comment]
It looks like we can pull the markup out of the main.js file. Maybe tomorrow.

https://github.com/scala/scala-lang/blob/master/resources/js/main.js#L133

**Comment by ashawley** [comment]
I meant to delete that reference in the last PR, but I guess it got lost when I was rebasing after Fabien's commit.

I'm not sure if re-using the old markup is possible.

I'll try reducing it to the "maximum" configured width for a tweet timeline which, according to Twitter's docs, is 520 pixels.  It should be a lot less prominent with the so-called "maximum".
