### ISSUE TITLE
Generate the spec using same Jekyll version

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#559]
So we recently got this repo and the docs.scala-lang repo onto modern Jekyll, but over in the scala/scala repo we're still on an older Jekyll (and, I notice, don't have a Gemfile.lock)

Opening the ticket in this repo because scala-lang.org is where the spec is hosted, even though it's built and uploaded by the `.travis.yml` in scala/scala.

Is there someone here who's comfortable enough with Jekyll and Ruby stuff to submit a PR in scala/scala bringing the infra there in line with our other repos?

**Comment by jarrodwb** [comment]
Yeah. I can git it a shot. I just started a new job two days ago but I think I will still have some time on the weekends for helping out.

Cheers.

**Comment by ashawley** [comment]
I created the pull request scala/scala#5593.

Changing the version number in the `Gemfile` brought Jekyll up-to-date with the other repos.  Doesn't seem like there's any need to use a `Gemfile.lock`, unless you wanted to track those changes.
