### ISSUE TITLE
Text color too "faded"

### ISSUE THREAD

**Issue by jkleiser** [scala/scala-lang#563]
As I said in a recent tweet, with text styled with "color: #586E75;", like here http://www.scala-lang.org/blog/2016/11/17/splash.html, I don't feel like I want to read it. Sorry.
It seems to be a general problem (for me) with the scala-lang pages, like this one here: http://www.scala-lang.org/documentation/. The text is too "faded". I have a quite good iMac from 2011, and a MacBook Air from 2015. I would suggest using "color: #333;", like here on github.com.

**Comment by jkleiser** [comment]
I also find the text on this page https://ruudvanasseldonk.com/2016/11/30/zero-cost-abstractions very easy to read. They use "color: #456;".

**Comment by jvican** [comment]
I agree, I don't read well low-constrast color schemes. @jkleiser Would you be up for submitting a PR?

**Comment by jkleiser** [comment]
No, I cannot do that now. I'm afraid the job should include more re-styling than just this single color.

**Comment by SethTisue** [comment]
duplicate of #509 ?

**Comment by jkleiser** [comment]
Yes, it's about text contrast, as in #509.

**Comment by SethTisue** [comment]
thanks @jkleiser for the report. (I should have remembered earlier that we already had an issue on this.)
