### ISSUE TITLE
2.13 spec should be available at http://www.scala-lang.org/files/archive/spec/2.13

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#567]
this might not sound urgent, but I suspect if we don't take care of it soon, the 2.13 spec will end up overwriting the 2.12 spec on the server. we already experienced this once with 2.11->2.12, details at https://github.com/scala/scala-lang/issues/479

@adriaanm can you wave your ssh forced-command wand at this?

the scala/scala piece is https://github.com/scala/scala/pull/5582 and will need to be merged first, I think

**Comment by adriaanm** [comment]
Server work done:
```
ssh scalatest@chara.epfl.ch -i ~/.ssh/for_chara
cd ~/.ssh/
cat authorized_keys2 | tail -n -2 | perl -pe 's/2.12/2.13/g' >> authorized_keys2 # or some manual approximation of that :-)
```

**Comment by SethTisue** [comment]
5582 is merged

**Comment by SethTisue** [comment]
@adriaanm http://www.scala-lang.org/files/archive/spec/2.12/ says "2.13" again. last time I checked it said "2.12", so it seems to go back and forth. maybe it depends on which Jenkins job happens to finish first

**Comment by adriaanm** [comment]
Ah I think I know what the issue is. Needed to generate a new keypair. Seems like you can't have multiple entries with different forced commands and the same public key

**Comment by adriaanm** [comment]
Looks like it's ok now: https://travis-ci.org/scala/scala/builds/183353137

**Comment by adriaanm** [comment]
https://github.com/scala/scala/commit/8066246f15964e33603ff1ca8f7ef27c98774483
