### ISSUE TITLE
Include contributors.scala-lang.org on the community page?

### ISSUE THREAD

**Issue by adamw** [scala/scala-lang#578]
I just found out about https://contributors.scala-lang.org (by chance on twitter).

I'd do a PR but I'm not sure how it relates to all the mailing lists (like scala-language, scala-debate) - is it a replacement?

**Comment by heathermiller** [comment]
Thanks @adamw for raising the issue. I've got a PR that's waiting to be made that'll update scala-lang with these things. Though you were exactly right; I was just waiting on consensus about how we'd handle the mailing lists. Will update the community page soon!

**Comment by adamw** [comment]
Ah I see - thanks for the info :)

**Comment by SethTisue** [comment]
fixed by #588
