### ISSUE TITLE
Events page not showing all events?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#587]
until recently http://www.scala-lang.org/events/ included several far-off events like Scala World 2017, but now they're missing?

is there some limit on how many events show up? if so, I suggest we remove that limit

cc @propensive

**Comment by heathermiller** [comment]
Seems the max is hardcoded to be 15 in the events js here: https://github.com/scala/scala-lang/blob/master/resources/js/main.js#L229

**Comment by SethTisue** [comment]
I lifted the limit in 47e02d056a84c4f4dfa06c1f351e9f6275c668d2 — wanted to get this in right away since scala_lang juuuuust tweeted about it

**Comment by propensive** [comment]
Ah, thank you. I spent a good five seconds looking for that limit before giving up and realizing it was easier to wait a few weeks for them to naturally appear!
