### ISSUE TITLE
The Website's width is off in some browsers.

### ISSUE THREAD

**Issue by DastardlyVandal** [scala/scala-lang#593]
On Chrome 56 for Fedora 25, the issue is present. However, in Firefox it is not.

Visiting the [getting started](https://www.scala-lang.org/documentation/getting-started.html) page and scrolling horizontally produces [this](http://i.imgur.com/O00fcz6.png)

Just a minor styling issue between browsers.

Edit: After a bit of poking around, it appears the issue is caused by a styling change made by javascript when scrolling down a little ways.

**Comment by SethTisue** [comment]
we should check to see if this got fixed in #606

**Comment by SethTisue** [comment]
assuming this got fixed by #606. if not let us know if we should reopen
