### ISSUE TITLE
"Did you know you can edit this page" badge on most pages

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#62]
As usual, I can do the styling stuff, so I'll take this one :-)

**Comment by SethTisue** [comment]
this would be a great enhancement. we should make this as easy as reasonably possible for a user to get to the GitHub UI for editing a page, without even having to clone the repo locally

**Comment by SethTisue** [comment]
if you visit e.g. http://www.lagomframework.com/documentation/1.2.x/java/LagomDesignPhilosophy.html

it says at the bottom:

> Found an error in this documentation? The source code for this page can be found **here**. Please feel free to edit and contribute a pull request.

where "here" is a link to the actual individual page on GitHub, e.g. https://github.com/lagom/lagom/blob/1.2.x/docs/manual/welcome/LagomDesignPhilosophy.md, from which you can hit the "Edit" button.

**Comment by SethTisue** [comment]
sbt did this for their website at https://github.com/sbt/website/pull/635

**Comment by ashawley** [comment]
This was done in the redesign last summer, #679

**Comment by dwijnand** [comment]
https://github.com/scala/scala-lang/blob/cd398a49aaa65d62e0fc5efbe8920e4f84438b0b/_includes/sidebar-toc.html#L9

:+1:

**Comment by SethTisue** [comment]
oh, okay, awesome!
