### ISSUE TITLE
bug reporting guide should reflect the JIRA -> GitHub move

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#631]
http://www.scala-lang.org/contribute/bug-reporting-guide.html points at JIRA, but the new hotness is https://github.com/scala/bug

**Comment by SethTisue** [comment]
once the page here is in good shape, the readme at https://github.com/scala/bug/blob/master/README.md could be replaced with just a single link to the page

**Comment by SethTisue** [comment]
@adriaanm suggests we get rid of the page here instead, and put all of the information in the readme in the bug repo

**Comment by SethTisue** [comment]
could be tackled in tandem with updating the scala/scala README.md and CONTRIBUTING.md. we should consolidate this stuff, I have no idea which of these things has what info, I assume nobody else does either

**Comment by adriaanm** [comment]
Similar for the jira filters linked from http://scala-lang.org/contribute/.

Let's try to be free from stale jira links before the end of the year. It's off-putting for a contributor to be presented with outdated information while they're looking for things to help out with

**Comment by SethTisue** [comment]
http://scala-lang.org/contribute/ could link to the `good-first-issue` label. context: https://contributors.scala-lang.org/t/help-wanted-identifying-good-first-issues-in-scala-bug/1571

**Comment by SethTisue** [comment]
(I've un-assigned myself to encourage community help on this)

**Comment by SethTisue** [comment]
> could be tackled in tandem with

but also, PRs with incremental improvements are very much welcome

**Comment by SethTisue** [comment]
> Let's try to be free from stale jira links before the end of the year

I double-checked just now to see if there was anything left to do after @Philippus's fine work

Fabien has put redirects in place so that any links to individual JIRA tickets are redirected to the corresponding scala/bug ticket (sample: https://issues.scala-lang.org/browse/SI-2689)

scala/scala is JIRA-link-free

scala/scala-lang only has JIRA links in old release notes

scala/docs.scala-lang has some JIRA links, but they are only to specific tickets, never to anything more general, so the redirects has it covered. even the remaining issue links are all in places that are crufty anyway (macros doc, quasiquotes doc, old SIPs, out of date translations...)

so I think we're good.
