### ISSUE TITLE
cdn.mathjax.org is shutting down

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#635]
see announcement at https://www.mathjax.org/cdn-shutting-down/

this will affect the language specification.

the needed change is actually in the scala/scala repo — we'll need to make the change on the 2.11.x branch and then merge it forward to 2.12.x and 2.13.x

(I don't think we archive old builds of the spec, so I don't think there's anything to go back and update there)

**Comment by SethTisue** [comment]
this Typelevel PR may be a useful reference: https://github.com/typelevel/typelevel.github.com/pull/163

**Comment by ashawley** [comment]
So just migrate the language spec to the cdnjs at Cloudfare?

Funny how the announcement reads.  I'm paraphrasing, but essentially "We can't afford to run the CDN on Cloudfare, so everyone needs to transitioning to running off of the CDN on Cloudfare".

**Comment by adriaanm** [comment]
I did this already. I pushed directly to the respective branches.

**Comment by adriaanm** [comment]
I'll propagate the change to 2.12 in the (hopefully) final merge from 2.11

**Comment by adriaanm** [comment]
https://github.com/scala/scala/pull/5851

**Comment by SethTisue** [comment]
OK, closing then since it's fixed on the 2.11 branch
