### ISSUE TITLE
Liquid doesn't render code blocks with tut

### ISSUE THREAD

**Issue by travissarles** [scala/scala-lang#639]
If you have a code block in your markdown with three back ticks ```tut, liquid will not render it. We need to figure out how to use [tut](https://github.com/tpolecat/tut) and liquid.

**Comment by tpolecat** [comment]
Why aren't you using the tut output? Is it just too much of a hassle to set up?

**Comment by SethTisue** [comment]
> Why aren't you using the tut output? 

previous discussion on this https://github.com/scala/scala.github.com/pull/593#issuecomment-251761233

it's future work for some motivated volunteer

**Comment by SethTisue** [comment]
@travissarles is this currently causing problems on the site?

**Comment by travissarles** [comment]
@SethTisue I'm making some changes to scala-lang and I noticed it wasn't wasn't rendering. However it was working fine with the Tour of Scala so maybe it's a matter of copying over whatever configuration is in the scala.github.com repo.

**Comment by SethTisue** [comment]
I wonder if this is still even an issue...

**Comment by jvican** [comment]
probably not, let's close it since tut works just fine. if somebody complains we can reopen!
