### ISSUE TITLE
Should add a commercial support page to the site

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#64]
It should highlight Typesafe as the main Scala supporter. There should be a link to this page in the footer, probably under the "Scala" subsection.

Point of debate– should it also give other consulting firms an opportunity to list themselves? 

I'd vote yes on principle, we definitely want our ecosystem to grow, but independent consultants that would lapse (get another job, whatever) would cause this page to frequently get outdated. I'd like to avoid the drama of pages going outdated as quickly as most of (old) scala-lang went outdated...

**Comment by SethTisue** [comment]
this has been dormant for a long time. I don't think it's a priority for Lightbend. and yeah, I agree about the difficulty of keeping it accurate/up-to-date. tentatively closing.
