### ISSUE TITLE
Can't ctrl-click/Cmd-click on links

### ISSUE THREAD

**Issue by Blaisorblade** [scala/scala-lang#644]
I often open links in new tabs by Cmd-click on OS X. That typically fails on scala-lang.org. Take https://www.scala-lang.org/contribute/documentation.html#updating-scala-langorg
Strangely, the link to http://docs.scala-lang.org/contribute.html works OK, but the one to https://github.com/scala/scala-lang doesn't.

Probably some JavaScript interfering? Maybe related to 
https://github.com/scala/scala-lang/issues/91#issuecomment-235873979

**Comment by megri** [comment]
What does the spree-label mean? I could take a stab at this if no one else wants to

**Comment by heathermiller** [comment]
Go for it! (Spree means it was suggested as a ticket for someone to work on during one of our [open source sprees](https://github.com/scalacenter/sprees))

**Comment by megri** [comment]
Damn, missed out on that swaggy t-shirt. I'll give it a try anyhow!

**Comment by megri** [comment]
[These lines in main.js](https://github.com/scala/scala-lang/blob/master/resources/js/main.js#L456-L459) are what's causing the problem. The click event gets eaten and the user is 200ms later redirected forcefully using `location.href`.

I guess the intent is to give _gaq.push time to register the action. Unfortunately the original event is eaten.

**Comment by megri** [comment]
Would you be fine with removing these lines? It's the quickest fix to solve the issue. As it stands there are other issues with how the script gets added — it doesn't attach to anchors whose href-attribute ends with ".html" for one, which is why the link to http://docs.scala-lang.org/contribute.html works as users expect.

**Comment by SethTisue** [comment]
perhaps Google Analytics has newer code available...?

**Comment by megri** [comment]
The library currently used is deprecated in favour of Universal Analytics. More stuff would have to be changed, potentially affecting the tracking in some way. From my end it's hard to tell.

**Comment by megri** [comment]
Maybe it'd be possible to remove the custom click handler altogether if we use UA instead. [Info here](https://developers.google.com/analytics/devguides/collection/analyticsjs/)

**Comment by megri** [comment]
Does anyone have a comment on my PR?

**Comment by SethTisue** [comment]
@megri sorry for the delayed feedback. we're a bit swamped now with fallout from the recent merge of the big redesign.

proposal:
* let's go ahead and merge this
* but also open a new ticket on upgrading to analytics stuff that isn't deprecated

if there isn't any further feedback, I'll hit "merge" in a few days

**Comment by SethTisue** [comment]
> but also open a new ticket on upgrading to analytics stuff that isn't deprecated

@megri would you mind opening the ticket, since it sounds like you already did some investigation?

**Comment by heathermiller** [comment]
No worries, I'll take care of it. I've got to fix analytics stuff anyway
