### ISSUE TITLE
Confusing structure for news list

### ISSUE THREAD

**Issue by Blaisorblade** [scala/scala-lang#645]
https://www.scala-lang.org/news/releases-1Q17.html is not on https://www.scala-lang.org/news/.

EDIT: sorry, it's just hidden, after all news and blog posts ever since 2013.

**Comment by travissarles** [comment]
@Blaisorblade can we close this?

**Comment by Blaisorblade** [comment]
I left it open as "hidden" still seems a usability bug rather than a design choice. How is an announcement not news? Why are some sections mixed and others not?

**Comment by SethTisue** [comment]
I find this highly confusing as well and would welcome a rethink.

**Comment by ashawley** [comment]
This was previously #197, but there has been a lot more news since then, so the fix didn't scale.

**Comment by heathermiller** [comment]
Now fixed in redesign: https://www.scala-lang.org/blog/news/
