### ISSUE TITLE
No link from blog posts/news items to list of 

### ISSUE THREAD

**Issue by Blaisorblade** [scala/scala-lang#646]
Try to click somewhere in https://www.scala-lang.org/news/releases-1Q17.html to get to https://www.scala-lang.org/news/.

Or try to get from https://www.scala-lang.org/blog/2017/02/27/scalafix-v0.3.html to https://www.scala-lang.org/blog/ by links.

I just noticed there's a link snuck at the bottom right in the end (after three times I've been on the verge of filing an issue). Could we have something more prominent at the top? I feel it's a small but not insignificant usability issue.

**Comment by heathermiller** [comment]
Now fixed in redesign (blog link on the top of every page)
