### ISSUE TITLE
more useful news items / GSOC page

### ISSUE THREAD

**Issue by cvogt** [scala/scala-lang#65]
Scala RC's and Milestones seem to flood the news list on the home page pushing other news away. At the same time superseded RC's and Milestones are of very limited interest. Maybe the news items should include only the latest release announcement per Scala version. Possibly a simple text-based filter could implement that, if jekyll supports this.

http://www2.scala-lang.org:8888/news/2013/03/20/gsoc13.html is currently a news item. Not sure that's really the right place for it. Maybe it is.

**Comment by SethTisue** [comment]
this got fixed at some point. http://www.scala-lang.org/news/ has two separate sections
