### ISSUE TITLE
design issues

### ISSUE THREAD

**Issue by cvogt** [scala/scala-lang#66]
http://www2.scala-lang.org:8888/news/2013/04/11/student-talks-sw13.html
Heading too long / overlaps
## 

http://www2.scala-lang.org:8888/news/2013/03/20/gsoc13.html
The ordered list numbers look odd.
## 

release notes
http://www2.scala-lang.org:8888/news/2013/03/13/release-notes-v2.10.1.html
http://www2.scala-lang.org:8888/news/2013/02/28/release-notes-v2.9.3.html
etc.
- use \* instead of bullet points for nested lists
- pretty cramped tables, which are hardly readable
- center table cells vertically, but vertical-align: top would probably be better

**Comment by SethTisue** [comment]
if someone still sees issues here, please open one or more fresh tickets with fresh links
