### ISSUE TITLE
release notes page on scala-lang doesn't obviously link to 2.11.11 and 2.12.2 notes

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#663]
http://www.scala-lang.org/download/#Release_Notes links to http://www.scala-lang.org/news/#announcements--changelog but there is no sign of 2.11.11 or 2.12.2 at either location

(thanks to ilmari on #scala IRC for the report)

**Comment by SethTisue** [comment]
the latter URL does have a "Three new releases and more GitHub goodness!", but to someone who is just looking for the release notes for a particular version, it isn't really satisfactory. the IRC user missed it, and I didn't see it until the second time I visited the page.

**Comment by adriaanm** [comment]
The idea is that we should use the release note feature on github, so the fix for this issue would be to update the link. Is that the intent? If so, I'm happy to make the change.

**Comment by DarkDimius** [comment]
For Dotty I've decided to have a single link in https://github.com/lampepfl/dotty/releases that refers to a github-tracked file.
This allows to maintain release notes with commit history and use normal editors to modify them.

**Comment by SethTisue** [comment]
> The idea is that we should use the release note feature on github, so the fix for this issue would be to update the link to https://github.com/scala/scala/releases. Is that the intent? If so, I'm happy to make the change

The best quick fix I can think of is to do that, but to also include the old link, for two reasons:

1) the GitHub release notes only go back to July 2013
2) and the GitHub UI doesn't make it easy to find a specific older version

Before too much longer 2 is going to get pretty annoying, but we could cross that bridge later.

Dima's suggestion is interesting, but on this ticket I was really just looking to fix the immediate usability problem.

**Comment by SethTisue** [comment]
another victim claimed: https://gitter.im/scala/contributors?at=5937df7531f589c64f82bb73
