### ISSUE TITLE
Page which spells out exactly which level of support people can expect from which platform

### ISSUE THREAD

**Issue by soc** [scala/scala-lang#67]
It is mentioned a bit in the "Scala runs on the JVM [...]", but we should make it more clear, which versions (5 deprecated, 6 and up supported) are supported and which implementations are tested and verified that they work (OpenJDK/Hotspot ... anything else?).

Additionally, it would be nice to stop ignoring all the work people have done to get Scala running on Android and mention that too (and link to the appropriate resources/mailing lists).

Mentioning the JavaScript backend and Avian support, marked as "experimental" would make sense imho, too.

**Comment by SethTisue** [comment]
https://github.com/scala/scala-lang/pull/506 addresses this slightly, but we should still do more. but I do think it should be done in a way that doesn't simply present the platforms as equal:
* JVM is still the flagship platform
* Scala.js is a strong second
* Scala Native is still very experimental
* Scala-on-Android deserves mention, especially now that http://scala-android.org exists, but (especially now with the release of Scala 2.12) we shouldn't oversell it

**Comment by SethTisue** [comment]
#606 does something towards this

**Comment by SethTisue** [comment]
new ticket on Scala Native specifically: #860

**Comment by SethTisue** [comment]
I think this ticket is too broad to leave open indefinitely. Some pieces have happened, like Scala.js getting much higher billing than it used to have.

I invite people to open more specific tickets like #860 on changes in this area they would like to see — or better yet, pull requests!
