### ISSUE TITLE
Blog posts are design-less

### ISSUE THREAD

**Issue by DarkDimius** [scala/scala-lang#681]
Main page looks nice now, but the blog entries are plain.

See,
http://scala-lang.org/blog/2017/07/12/second-dotty-milestone-release.html
which is in the first line of the main page now.

**Comment by DarkDimius** [comment]
Other blog posts have the same issue: http://scala-lang.org/blog/2017/07/02/collections-0.2.0.html

**Comment by heathermiller** [comment]
Yes I know. I'm in the middle of merging the new scala-lang design. I already fixed this. Thanks!
