### ISSUE TITLE
Documentation link gives HTTPS error

### ISSUE THREAD

**Issue by DarkDimius** [scala/scala-lang#682]
On both chrome and firefox

**Comment by heathermiller** [comment]
I know, a fix is already in-progress.

**Comment by heathermiller** [comment]
Btw, cc/ @fsalvi (so you know why I pinged you about this earlier today. It's blocking people from getting to the documentation pages, so the sooner we can move to EPFL machines ASAP the better)

**Comment by fsalvi** [comment]
I changed the URL to http instead of https.
This will let us time to fix the problem...

**Comment by SethTisue** [comment]
this was fixed some time ago.
