### ISSUE TITLE
Where do I download old versions?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#686]
http://www.scala-lang.org/download/ doesn't seem to have a link, anymore, where you can get to other versions besides 2.12.2

**Comment by SethTisue** [comment]
oh, there is this, all the way at the bottom of the page:

<img width="204" alt="screen shot 2017-07-13 at 9 54 13 am" src="https://user-images.githubusercontent.com/161079/28170060-2ca0d29e-67b2-11e7-82c5-e30bf093f7fe.png">

but I really didn't expect to have to "exit" the current context and go all the way to the top level context to find this (and it didn't used to be like that)

**Comment by heathermiller** [comment]
I already fixed this. There was a permalink added that broke everything, and a link to all versions removed from the mockup. It's coming as soon as I commit the rest of the changes to the download page, no worries.

**Comment by heathermiller** [comment]
Should be fixed in #689.

If you're unhappy with the solution in that PR, please reopen. Thanks!
