### ISSUE TITLE
"Release notes" and "Changelog" links both go to the same place

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#687]
http://www.scala-lang.org/download/ has:

<img width="264" alt="screen shot 2017-07-13 at 10 02 24 am" src="https://user-images.githubusercontent.com/161079/28170144-70c446ea-67b2-11e7-812c-5b92ca354430.png">

but then both links go to the same URL, http://www.scala-lang.org/download/changelog/

which is a page I don't recall ever having seen before, and is not all that helpful (it has the major version changes but not the minor versions)

**Comment by heathermiller** [comment]
Yeah, I know. I'm working on redoing the download page now.

Can you tell me how you want me to link to the release notes and changelog?

**Comment by SethTisue** [comment]
see "the PR of the beast": #666

**Comment by heathermiller** [comment]
Gah.
