### ISSUE TITLE
We probably need to put back the "additional information" box

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#691]
Seems this one got lost too in the proposed redesign.

E.g.,
![screen shot 2017-07-13 at 5 16 55 pm](https://user-images.githubusercontent.com/687163/28173561-19aab10e-67ef-11e7-8e25-231c3779b0c9.png)

**Comment by ashawley** [comment]
It's still in the repo just not being included in the page?

https://github.com/scala/scala-lang/blob/10e462e/download/index.md

Just not being included on this template:

https://github.com/scala/scala-lang/blob/10e462e/_layouts/downloadpage.html

Done accidentally in this commit 2e8681f?

**Comment by ashawley** [comment]
Seems it should be included in the layout of the layout, but it doesn't show up:

https://github.com/scala/scala-lang/blob/10e462e/_layouts/inner-page-parent.html

**Comment by heathermiller** [comment]
Thank you 💯 @ashawley!!
