### ISSUE TITLE
Training feed on front page broken

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#698]

**Comment by SethTisue** [comment]
confirmed that the training added in #754 shows up on the site

**Comment by heathermiller** [comment]
This still isn't fixed, unfortunately. There are a ton of training events that Lightbend publishes to a feed that would normally show up in this feed... So I'm afraid htat #754 didn't fix the issue (at least as I understood it, and I admit I offered zero detail about it. I'm sorry!)

https://github.com/scala/scala-lang/pull/754#issuecomment-333827084

**Comment by heathermiller** [comment]
This is the feed we used to be fetching btw... https://www.lightbend.com/subscription/training.json

**Comment by heathermiller** [comment]
And this is where we were doing the fetching:
https://github.com/scala/scala-lang/blob/master/resources/js/main.js#L428

(Like I said, I've not looked into it yet. But this is what I had meant when I opened this ticket)

**Comment by ashawley** [comment]
Ahh sorry, I didn't understand what was meant by broken.  Now I do.

**Comment by heathermiller** [comment]
That was my fault, I'm sorry! I should've been way more descriptive than I was 🙈

**Comment by SethTisue** [comment]
I'll take it up with somebody at Lightbend.

**Comment by SethTisue** [comment]
I was able to fix this myself in 35c0bb2143247f35c051239fd88ad994c39583eb

**Comment by heathermiller** [comment]
Call me crazy, but it still seems broken to me. None of those feeds from the Lightbend training feed seem to be coming through:
<img width="1277" alt="screen shot 2017-10-04 at 8 56 00 am" src="https://user-images.githubusercontent.com/687163/31163297-19c89c94-a8e2-11e7-9694-daca72d36905.png">

**Comment by heathermiller** [comment]
(I think this is an issue on our end somewhere btw. I'm not sure this is something Lightbend can fix.)

**Comment by SethTisue** [comment]
my change did fix _something_ — before, nothing showed up on the right. now, that "Scala Language — Professional" entry shows up

but yes, you are right, it still isn't working. https://www.lightbend.com/subscription/training.json has more than just that one item. so a guess at the remaining bug, now, is that only the first item in the JSON file is shown.

**Comment by ashawley** [comment]
Heather drives a hard bargain! 😃 

Looks like `main.js` was removed from `footer.html` in 2bdcd90f.  Including `main.js` again causes  errors to be thrown.  Maybe just take the training (and Scala events?) bits and move them from `main.js` to `function.js`?  There's a bit of AJAX work to get it going again after that.
