### ISSUE TITLE
add redirect for old code of conduct URL

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#700]
it would be nice to have a redirect from http://scala-lang.org/conduct.html to the new URL http://scala-lang.org/conduct/ , since there are a lot of links to the old URL out there

**Comment by SethTisue** [comment]
(fwiw, I changed the URL in a bunch of Gitter channel topics, but I probably missed some)

**Comment by heathermiller** [comment]
Feel to get rid of those permalinks. They were added by someone thinking they'd simplify URLs but without realizing that they'd break a ton of existing links into scala-lang. I've been going around one by one and removing them. If you see some, feel free to remove them too.

**Comment by heathermiller** [comment]
I've been getting rid of permalinks since Thursday. This is one that I missed. So, help welcome!

**Comment by SethTisue** [comment]
this is a case where a permalink was apparently removed, rather than added. I hope 4b07f9ba705229af0f5f810fb5de91c5f440a8ce is the right way to keep `/conduct/` as the canonical URL but also keep the `/conduct.html` link working, since I think both URLs are now floating around out there
