### ISSUE TITLE
Problem with this page? links broken

### ISSUE THREAD

**Issue by heathermiller** [scala/scala-lang#704]
On some pages, the "Problem with this page? Please help us fix it!" links are broken.

Related to permalinks? /shrug
http://scala-lang.org/license/
http://scala-lang.org/community/
http://scala-lang.org/contribute/

But works on the blogs/news/announcements pages 🤔 
http://scala-lang.org/blog/2017/05/31/first-dotty-milestone-release.html

**Comment by jiminhsieh** [comment]
Hi @heathermiller https://github.com/scala/scala-lang/pull/725 should fix this issue.

**Comment by heathermiller** [comment]
Thanks for the ping, @jiminhsieh!
