### ISSUE TITLE
"Getting Started" link is now broken

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#705]
on scala-lang.org front page:

<img width="240" alt="screen shot 2017-07-17 at 1 10 15 pm" src="https://user-images.githubusercontent.com/161079/28280312-5b49fc0a-6af1-11e7-941b-8bc3dce7a68e.png">

the "getting started" link goes to http://scala-lang.org/documentation/getting-started/ which doesn't exist

**Comment by SethTisue** [comment]
a similar report but for a different URL, not sure where from: https://twitter.com/ChrisJamesC/status/885509256350507012

**Comment by heathermiller** [comment]
Yeah, I'm currently working on https://github.com/scala/scala.github.com/pull/806. When that's done, this link should be reachable.
