### ISSUE TITLE
[minor] Google linking to 2.5.1 docs? SEO issue?

### ISSUE THREAD

**Issue by Blaisorblade** [scala/scala-lang#708]
That's maybe just a small disturbance in the force (or a link from some crazily popular blog post), but was just led to http://www.scala-lang.org/api/2.5.1/scala/List.html by googling `:::`.
More importantly, does this mean scala operators are somehow googlable? (Yes, sorry, I have NO clue on SEO and it must show, have mercy upon me).

Links:

https://www.google.it/search?client=opera&q=list+%3A%3A%3A&sourceid=opera&ie=UTF-8&oe=UTF-8#q=scala+list+:::

![Google results for scala list ::: link to docs for ultra-old Scala 2.5.1.](https://pbs.twimg.com/media/DFD3KLDWsAAMjEM.png)

(https://twitter.com/Blaisorblade/status/887481363376594949)

**Comment by Philippus** [comment]
Google now leads me to 2.12.3, so that's better I guess

**Comment by Blaisorblade** [comment]
Happy to close this as fixed, even though I'm not sure if there's any other SEO to do.
