### ISSUE TITLE
Scala downloads: "All Available Versions" doesn't include recent versions

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#714]
http://scala-lang.org/download/all.html claims to be "ALL AVAILABLE VERSIONS" and "This page contains a comprehensive archive of previous Scala releases" but it isn't, e.g. 2.11.11 is missing

**Comment by SethTisue** [comment]
cc @retronym (who's doing the 2.12.3 release)

**Comment by som-snytt** [comment]
I commented https://gitter.im/scala/contributors?at=5979140f89aea4761dd90b23

> There are nice new download pages. But I noticed the http://www.scala-lang.org/download/all.html all previous page is not sorted, or reverse-sorted. I also wonder if the all page should include the current release for each series. Then it would be obvious that the series goes 2.11.11, 2.11.8, etc. That's the sort of thing that matters if you're looking at the list of all releases. Maybe the most-current in each series could be highlighted in a fancy color.

Then Ichoran noted that "fancy color" denotes grades of colored diamonds. 

> The latest releases are truly jewels.

I suggested "fancy red", the highest and rarest grade, for future Scala t-shirts.

Or "vivid pink" for Scalabridge benefit.

My daughter used to have a pink "Superman" shirt from Old Navy. That was a few years before Supergirl. It was a big hit at Cisco daycare.

I'd pay top dollar (or euro) for a pink spiral t-shirt signed by the core team (including Martin). And Bridge folks like Heather and Rahel Lüthy. I'd have to get two, one for her to wear and one for my collection.

Someone said I looked like a superhero in my contributor t-shirt (thanks, @SethTisue), that was either my daughter or my colleague, the only two people talking to me.

Reference https://www.nytimes.com/2017/07/26/business/colored-diamonds.html

**Comment by som-snytt** [comment]
Also, the line of text on the page does say "previous", but it would be more useful just to list all versions, sorted by timeline. I think the `ScalaVersion` class already knows how to order itself.

**Comment by heathermiller** [comment]
Since the Lightbend Scala team manages releases, I assume whoever is in charge of pushing the release button on a new version of 2.12.x or 2.11.x should update the "all available versions of Scala" page as part of the release process. Should probably be added to the release todos checklist, no?

**Comment by retronym** [comment]
Yes, that's right. We have [tools](https://github.com/scala/make-release-notes) to generate the patch to this site. We need to adapt them to the refactored layout here, and double check our checklist. I did a few things manually for 2.12.3, but plan to take another pass over the site and the tooling to cleanup any inconsistencies and improve the automation level.

**Comment by retronym** [comment]
One thing I was wondering, is whether it would be feasible to dynamically generate the "all previous releases" page. I'm not sure about the limits of Jekyll in this regard.

**Comment by SethTisue** [comment]
> it would be feasible to dynamically generate the "all previous releases" page.

I believe that would mean pushing the logic into client-side JavaScript. Doesn't seem worth it here.

**Comment by heathermiller** [comment]
I think this was fixed in #723 (thank you @zaneli!!). Though @retronym, I presume you'll still have to update where you guys place these files in your release process.

**Comment by heathermiller** [comment]
Closing this for now, reopen if there's something we need to do in this repo.
