### ISSUE TITLE
code not styled using monospaced font

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#722]
seen at e.g. http://www.scala-lang.org/news/2.12.0/ :

<img width="384" alt="screen shot 2017-08-09 at 12 17 23 pm" src="https://user-images.githubusercontent.com/161079/29139710-b8014e54-7cfc-11e7-8526-e4be3477e4ea.png">

perhaps it needs the same fix that was applied over at the docs site for https://github.com/scala/scala.github.com/issues/839 ?

**Comment by heathermiller** [comment]
Thanks for letting me know I missed it here too! Should be fixed now.
