### ISSUE TITLE
"Scala code of Conduct" file not found on scala-lang.org

### ISSUE THREAD

**Issue by alejopa** [scala/scala-lang#728]
You get "page not found" when trying to access the code of conduct.

**Comment by SethTisue** [comment]
where is the broken link? the link on the front page works.

**Comment by heathermiller** [comment]
Same here, I can't seem to find a broken link to the Code of Conduct anywhere, neither on scala-lang.org or docs.scala-lang.org. 

Could you tell us where you saw this? We're happy to fix this right away if you can point us to the location of the problem.

Thanks!

**Comment by alejopa** [comment]
Sure, in https://www.scala-lang.org/community/ there's a link to: https://www.scala-lang.org/conduct.html
and that page is not found. 
Here you can see the link
![image](https://user-images.githubusercontent.com/4819785/29417210-c7fabb36-833e-11e7-8bbf-fdcb11dac3f4.png)

![image](https://user-images.githubusercontent.com/4819785/29417158-9ebdb458-833e-11e7-9783-5d650408f851.png)

**Comment by heathermiller** [comment]
Ok, got it. Thanks for sharing! I'll take care of it now :)

**Comment by alejopa** [comment]
Great! thanks.
