### ISSUE TITLE
Steps on getting started page need clarification

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#747]
at https://github.com/scala/bug/issues/10499 @cfjedimaster writes:

> I'm learning Scala and going through the Getting Started page here (https://www.scala-lang.org/documentation/getting-started-sbt-track/getting-started-with-scala-and-sbt-on-the-command-line.html). 

> Step 1 under "Running the project" says to "cd into hello-world." and then run sbt. However, doing so will throw an error saying no main class was defined.

> If I CD'ed into hello-world-template (which is where the new folder was created, not hello-world), and *then* CDed into project, sbt ran as expected.

**Comment by Philippus** [comment]
Looks like you missed the following step in 'create the project':
"When prompted, name the application hello-world. This will create a project called “hello-world”.
'hello-world-template' is the default which is applied if you don't name the application and just hint 'enter'.

**Comment by outkaj** [comment]
I just went through the "getting-started" page step by step to see if this bug still occurred. It did not, and it looks like the clarification mentioned by @Philippus has been added, so maybe this can now be closed?

**Comment by SethTisue** [comment]
I haven't re-reviewed this, but, closing based on @outkaj's comment.
