### ISSUE TITLE
Getting started pages should be clear about JDK version compatibility

### ISSUE THREAD

**Issue by abellgithub** [scala/scala-lang#761]
Installing the recommended scala version (2.11.8 for Mac) needs JDK 1.8.  This is stated in the "getting started" docs, but it's not made clear that later versions (JDK 1.9, for example) doesn't work (and gives a non-obvious error).  The docs should say this and tell people how to verify and switch to the correct JDK on their platform.

**Comment by SethTisue** [comment]
where is 2.11.8 recommended? that sounds like a problem in itself, the recommended version should be 2.12.3

2.11.8 isn't even the latest 2.11.x release — that would be 2.11.11

**Comment by colindean** [comment]
I did a quick search for `2.11.8` just now off of master and came up only with version lists on

1. http://docs.scala-lang.org/api/all.html
2. http://docs.scala-lang.org/reference.html

```
$ rg -g '!*.svg' '2.11.8'
reference.md
25:* Scala 2.11.8
26:  * [Standard Library API](http://www.scala-lang.org/api/2.11.8/)
27:  * [Compiler API](http://www.scala-lang.org/api/2.11.8/scala-compiler/)
28:  * [Reflection API](http://www.scala-lang.org/api/2.11.8/scala-reflect/#scala.reflect.package)
30:    * [XML API](http://www.scala-lang.org/api/2.11.8/scala-xml/#scala.xml.package)
31:    * [Parser Combinators API](http://www.scala-lang.org/api/2.11.8/scala-parser-combinators/)
32:    * [Actors API](http://www.scala-lang.org/api/2.11.8/scala-actors/#scala.actors.package) (deprecated)
33:    * [Swing API](http://www.scala-lang.org/api/2.11.8/scala-swing/#scala.swing.package)
34:    * [Continuations API](http://www.scala-lang.org/files/archive/api/2.11.8/scala-continuations-library/#scala.util.continuations.package)

api/all.md
16:* Scala 2.11.8
17:  * [Library API](http://www.scala-lang.org/api/2.11.8/)
18:  * [Compiler API](http://www.scala-lang.org/api/2.11.8/scala-compiler/)
19:  * [Reflection API](http://www.scala-lang.org/api/2.11.8/scala-reflect/#scala.reflect.package)
21:    * [XML API](http://www.scala-lang.org/api/2.11.8/scala-xml/#scala.xml.package)
22:    * [Parser Combinators API](http://www.scala-lang.org/api/2.11.8/scala-parser-combinators/)
23:    * [Actors API](http://www.scala-lang.org/api/2.11.8/scala-actors/#scala.actors.package) (deprecated)
24:    * [Swing API](http://www.scala-lang.org/api/2.11.8/scala-swing/#scala.swing.package)
25:    * [Continuations API](http://www.scala-lang.org/files/archive/api/2.11.8/scala-continuations-library/#scala.util.continuations.package)
```

Maybe @abellgithub's discovery has been addressed in the meantime.

**Comment by ashawley** [comment]
Maybe when sbt 0.13.17 drops (next week?) there should be a blog post about the current Java 9 support in Scala-land, and the long-term plans wrt Java 9 and later...?  Then link to the blog post from the download page?

**Comment by ashawley** [comment]
Just saw @SethTisue suggested a longer-term document on scala/docs.scala-lang#1000

**Comment by SethTisue** [comment]
once https://github.com/scala/docs.scala-lang/pull/1005 is merged we'll have something to link to

**Comment by SethTisue** [comment]
http://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by SethTisue** [comment]
current status: Scala 2.11.12 and 2.12.4 have basic Java 9 compatibility, and so do sbt 0.13.17 and 1.1.1

**Comment by SethTisue** [comment]
I've changed the title of the ticket since the situation has changed somewhat.

**Comment by SethTisue** [comment]
this is no longer an issue now that the current Scala version (2.12.6) works fine on JDK 8, 9, and 10.
