### ISSUE TITLE
getting-started-intellij-track inconsistencies

### ISSUE THREAD

**Issue by NightFantomJ2** [scala/scala-lang#775]
I'm on linux, can someone confirm these issues exist on windows/mac/... intellij installations too?

### In https://www.scala-lang.org/documentation/getting-started-intellij-track/getting-started-with-scala-in-intellij.html :
in "[Writing Code](https://github.com/scala/scala-lang/blob/master/documentation/getting-started-intellij-track/getting-started-with-scala-in-intellij.md#writing-code)" it says
>On the Project pane on the left, right-click src and select New => Scala class.

but this doesn't work as the src folder isn't treated as a scala source folder. Instead, this should be something like
> right click the "scala" folder in src/main/ and select New => Scala class

### In https://www.scala-lang.org/documentation/getting-started-intellij-track/building-a-scala-project-with-intellij-and-sbt.html : 
in "[Running the project](https://github.com/scala/scala-lang/blob/master/documentation/getting-started-intellij-track/building-a-scala-project-with-intellij-and-sbt.md#running-the-project)" it says 
> In the code, change currentYear - 1 to ` currentYear - 2` and look at the updated output in the console.

but there is no "currentYear" in the example code. I assume the example came from somewhere else but even the earliest commit has this issue. I suggest changing the line with the ages into other numbers instead.

**Comment by mghildiy** [comment]
Hi, in windows 10 IntelliJ installation too I need to
right click the "scala" folder in src/main/ and select New => Scala class

**Comment by mghildiy** [comment]
I have made the change in getting-started-with-scala-in-intellij.md and committed it. I have also created the pull request:
https://github.com/scala/scala-lang/pull/806

So I hope someone would review it.

**Comment by Philippus** [comment]
fixed by https://github.com/scala/scala-lang/pull/806
