### ISSUE TITLE
Some texts are too small

### ISSUE THREAD

**Issue by Dinduks** [scala/scala-lang#79]
Hi, 

There are the concerned texts. 
Some are even harder to read due to the lack of contrast. 

![screen shot 2013-07-30 at 16 27 34](https://f.cloud.github.com/assets/504977/879237/66f28a74-f924-11e2-86c8-eb6d89e09170.png)
![screen shot 2013-07-30 at 16 27 37](https://f.cloud.github.com/assets/504977/879238/67038b62-f924-11e2-95ec-137b1dfdae52.png)
![screen shot 2013-07-30 at 16 27 44](https://f.cloud.github.com/assets/504977/879239/671322fc-f924-11e2-9967-814b6e5e290f.png)
![screen shot 2013-07-30 at 16 27 47](https://f.cloud.github.com/assets/504977/879240/6715e546-f924-11e2-8298-bc2c32847dc8.png)
![screen shot 2013-07-30 at 16 27 56](https://f.cloud.github.com/assets/504977/879241/671d0be6-f924-11e2-9c35-7ce48a01df9a.png)
![screen shot 2013-07-30 at 16 28 04](https://f.cloud.github.com/assets/504977/879242/671b6b60-f924-11e2-99ef-993f9d0c376e.png)
![screen shot 2013-07-30 at 16 27 51](https://f.cloud.github.com/assets/504977/879244/671eed08-f924-11e2-9075-dd90f8196b58.png)
![screen shot 2013-07-30 at 16 28 02](https://f.cloud.github.com/assets/504977/879243/671de07a-f924-11e2-8951-fb920c5bc858.png)

**Comment by SethTisue** [comment]
possibly fixed by #606? we should check

**Comment by Dinduks** [comment]
@SethTisue The texts I showed are still tiny. :)

**Comment by SethTisue** [comment]
at the time, #606 hadn't been merged yet, but now it has.
