### ISSUE TITLE
Bloop performance numbers, speedup calculations

### ISSUE THREAD

**Issue by Blaisorblade** [scala/scala-lang#796]
Hi @jvican! The bloop announcement looks cool! But I was a bit surprised by some (EDIT) text, so I clicked the “help us fix it” link and got here. Quoting: https://github.com/scala/scala-lang/blob/master/blog/_posts/2017-11-30-bloop-release.md

> To put those numbers into context, the speedup observed in apache/spark is equal to the compilation speedup that Jason Zaugg introduced in the 2.12.x series. That means that when Spark developers migrate to 2.12 and use bloop, they will experience a compilation speedup close to 80% (40% from upgrading to Scala 2.12.x, 40% from using bloop).

Summing speedups (or discounts) seldom works, because those percentage usually have different bases.

If you consistently take 1.4x speedup as “old time = 1.4 * new time”, as Wikipedia suggests (not “new time = 60% of old time”), the new runtime would be 1/(1.4^2) = 1/1.96.
Since this is pretty confusing to explain, presentation-wise, if you want to show this I would maybe show estimates of compilation times and call them as such (estimates/extrapolations) — if you think it’s worth showing this extrapolation.

But I can’t get 1.4 either way for apache/spark, so I’m confused — 159/107 is 1.48598..., which rounds to 1.5. With that formula, there seem to be bigger deviations for scala/scala and sbt/sbt.

(There’s also a hot/cold typo, see https://github.com/scala/scala-lang/pull/794#issuecomment-348306627).

**Comment by jvican** [comment]
Hey @Blaisorblade, indeed this is a stupid error, a proof that you should not write blog posts under stress. I fixed the percentage by hand but I will reply to this ticket more succinctly tomorrow.

**Comment by Blaisorblade** [comment]
Hey—don’t worry, I’ve submitted worse typos under deadlines :-|. Thanks for fixing the typo! (Not sure about the speedups in the table though, but maybe that’s me?).

**Comment by SethTisue** [comment]
@jvican ping

**Comment by jvican** [comment]
I think I’m going to hire you as my personal assistant @SethTisue, thanks for the reminder!

To address your last comment @Blaisorblade, the raw numbers for spark and Scala are the correct, the percentage was derived from it. So if it seems that bloop is faster than what we announced, that’s even better. We’ve been working hard on stable benchmarks infrastructure and automatic benchmarking, si hopefully you’ll be able to track future variations in the future. I expect this to be fully operative in one week.
