### ISSUE TITLE
Mention native target on landing page

### ISSUE THREAD

**Issue by tindzk** [scala/scala-lang#860]
As per [my comment](https://github.com/scala/scala-lang/pull/854#issuecomment-374941877) on the changes to the landing page, I would suggest to also mention Scala Native.

This issue is related: https://github.com/scala/scala-lang/issues/67

**Comment by SethTisue** [comment]
/cc @densh 

the hesitation on this so far has been that Scala Native is substantially less mature than Scala.js.

in addition to the wording at the top, there's also this section:

<img width="459" alt="screen shot 2018-03-21 at 11 13 40 am" src="https://user-images.githubusercontent.com/161079/37718388-f2ec9f76-2cf8-11e8-8360-adda3b8ad464.png">

**Comment by SethTisue** [comment]
an older ticket on this (but broader) is https://github.com/scala/scala-lang/issues/67

my own take on this is that it's too soon to give Scala Native equal billing, but perhaps we could find some middle ground. (especially with that "with more backends on the way" which is an undersell; Scala Native does exist.)

**Comment by tindzk** [comment]
I do not think it is wrong to attract developers to Scala Native at this stage. Based on my limited experience, Scala Native already works pretty well for regular Scala code, although library support is still spotty. How about including the Scala Native logo with a clearly visible sign that says "beta"? Then, the remark "with more backends on the way" could be removed.

**Comment by ashawley** [comment]
Things like Scala.js and native are nice things to brag about, but there is a risk with suggesting them to newcomers.  My experience is that they are expert tools and not for the faint of heart.  It's not a polished or well-supported system like Scala on the JVM is.

**Comment by propensive** [comment]
I would be in favor of including Scala Native in the list of backends, but maybe with a "beta" (or similar) label. Given the current nature of the market, I don't think it makes sense to keep quiet about things like this. The current text "WITH MORE BACKENDS ON THE WAY" won't appeal to anyone: almost everyone will be interested in a specific backend.

**Comment by heathermiller** [comment]
I think this is a call for @densh to make. We should not be deciding the readiness of his project for him.

**Comment by densh** [comment]
I don't mind Scala Native having a "beta" sticker of some sort at all. It did not reach 1.0-level of stability yet.

The line "more backend on the way" conveys no information. It's going to *only* be understood by people who already know about SN, and the rest will not grasp what it alludes to.

**Comment by propensive** [comment]
Implemented with #867.

**Comment by tindzk** [comment]
Looks great! Thanks, @propensive.
