### ISSUE TITLE
HTTPS issue。

### ISSUE THREAD

**Issue by hepin1989** [scala/scala-lang#863]
Should redirect `http://scala-lang.org/` to `https://scala-lang.org/`。

**Comment by SethTisue** [comment]
I suspect this isn't possible for an open-source contributor to do.

@fsalvi is this within your area of expertise...?

**Comment by NthPortal** [comment]
This seems like something the server admin needs to handle

**Comment by fsalvi** [comment]
Yes, I can do that. I will check first there are no side effects if we switch to https...

**Comment by fsalvi** [comment]
Ok, done.

**Comment by SethTisue** [comment]
@fsalvi awesome! I guess I should have said so earlier, but could you do docs.scala-lang.org as well...?

**Comment by fsalvi** [comment]
Yes, it was already planned. I will do it soon.

**Comment by fsalvi** [comment]
It's done for docs.scala-lang.org

**Comment by SethTisue** [comment]
@fsalvi fantastic, thank you!

ENCRYPT ALL THE THINGS!
