### ISSUE TITLE
Concurrency sample uses deprecated `future` function

### ISSUE THREAD

**Issue by kubukoz** [scala/scala-lang#876]
```scala
val x = future { someExpensiveComputation() }
val y = future { someOtherExpensiveComputation() }
val z = for (a <- x; b <- y) yield a*b
for (c <- z) println("Result: " + c)
println("Meanwhile, the main thread goes on!")
```

from the sources:
```scala
@deprecated("use `Future { ... }` instead", "2.11.0")
// removal planned for 2.13.0
def future[T](body: =>T)
```

The `future` usage should probably be replaced with `Future { }` in this example (and its description). If you think it's a good idea, I can prepare a PR in no time :)

**Comment by SethTisue** [comment]
yes please!

**Comment by kubukoz** [comment]
I can see that the correct version is used in `_includes/bullet-concurrency-distribution.html` since https://github.com/scala/scala-lang/pull/642 - why are there two places for these snippets?

Anyways, I should have a PR with a fix for this within minutes :)

**Comment by kubukoz** [comment]
It's ready in #878 :)
