### ISSUE TITLE
http://pgp.mit.edu/ causes intermittent htmlproofer failures

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#881]
perhaps we can exempt the domain from htmlproofer?

**Comment by dwijnand** [comment]
Additionally (I can split this into a separate issue) https://travis-ci.org/scala/scala-lang/builds/380079726 from https://github.com/scala/scala-lang/pull/896/commits/38c24d1f47304baee8e13fafba1c57ca5bae2e3c failed with:

```
- ./_site/documentation/your-first-lines-of-scala.html
  *  External link http://java.sun.com/javase/ failed: 403 No error
- ./_site/news/2.12.0/index.html
  *  External link http://www.oracle.com/technetwork/java/javase/downloads/index.html failed: 403 No error
htmlproofer 3.8.0 | Error:  HTML-Proofer found 2 failures!
```

**Comment by SethTisue** [comment]
I see at https://github.com/gjtorikian/html-proofer that a `--url-ignore` option is supported
