### ISSUE TITLE
Middle-clicking broken in some places

### ISSUE THREAD

**Issue by mpartel** [scala/scala-lang#91]
Middle-clicking items under "upcoming events" and "upcoming training" does nothing.

Middle-clicking `@usernames`, `#bugnumbers` and some ordinary-looking links under "What's new" opens them in the current tab.

**Comment by retronym** [comment]
Heres the culprit:

```
⚡ git grep window.location
resources/js/main.js:        '<div class="event-item-wrap '+additionalClass+'" onclick="window.location=\''+event.url+'\'">' +
resources/js/main.js:        '<div class="training-item-wrap '+additionalClass+'" onclick="window.location=\''+training.url+'\'">' +
```

**Comment by retronym** [comment]
Actually I think the problem is the way that google analytics is added
