### ISSUE TITLE
SSL Cert for https://downloads.lightbend.com/ expired

### ISSUE THREAD

**Issue by bachos** [scala/scala-lang#920]
I was trying to download a latest Scala binary from https://downloads.lightbend.com/ and it seems that the SSL cert expired in Jun 22.

I just want to let you guys know.

Cheers

**Comment by SethTisue** [comment]
(also reported by @DarkDimius on Gitter)

**Comment by SethTisue** [comment]
(I've raised this on Lightbend’s internal Slack)

**Comment by SethTisue** [comment]
I've heard this may be fixed now, can someone verify...?

**Comment by edwardcallahan** [comment]
Example: https://downloads.lightbend.com/cinnamon/docs/2.10.0-20180605-26e7708-streams/setup/cinnamon-agent-sbt.html

**Comment by SethTisue** [comment]
thanks @edwardcallahan!
