### ISSUE TITLE
upgrade Jekyll to 3.8.x?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#932]
we're on 3.5.2, https://jekyllrb.com is at 3.8.3. that seems like we've fallen pretty far behind

would someone like to take a look and see if this would be a desirable upgrade for us here (and on docs.scala-lang)?

**Comment by SethTisue** [comment]
optimistically labeled "good first issue", on two conditions:

* you'll need to already have, or acquire, a little basic knowledge of Jekyll and Gemfiles
* you might run into trouble, but even if you get stuck, it would still be valuable to have tried and to report back on the difficulty you encountered

**Comment by jan0sch** [comment]
I'm looking into this. Bundler refuses to update jekyll farther than 3.6 so I'm trying something else.

**Comment by jan0sch** [comment]
Okay, pull request created: #940
