### ISSUE TITLE
Events page no longer displays events

### ISSUE THREAD

**Issue by propensive** [scala/scala-lang#936]
The events page here,
https://www.scala-lang.org/events/
appears to momentarily display upcoming events, but quickly refreshes to display only a list of trainings.

I've not investigated why, but I've been relying for a while on this page to work out where in the world I need to be on any date. ;)

**Comment by Philippus** [comment]
This is a regression introduced in https://github.com/scala/scala-lang/pull/924. I've made a PR to fix it.
Ultimately the cause is too much code reuse between trainings and events. They are not so similar after all.

**Comment by propensive** [comment]
Thank you, @Philippus! It's great that I can raise an issue like this and about an hour later someone steps up to fix it!
