### ISSUE TITLE
Path and Environment

### ISSUE THREAD

**Issue by tldzyx** [scala/scala-lang#943]
[Path and Environment](https://github.com/scala/scala-lang/blob/master/download/install.md)

Why not
---

## Path and Environment

For quick access, add `scala` and `scalac` to your path. For example:

| Environment | Variable         | Value (example)
|:------------|:-----------------|:---------------
| Unix        | `$SCALA_HOME`    | `/usr/local/share/scala`
|             | `$PATH`          | `$SCALA_HOME/bin:$PATH`
| Windows     | `%SCALA_HOME%`   | `c:\Progra~1\Scala`
|             | `%PATH%`         | `%SCALA_HOME%\bin;%PATH%`

---

the path is serial, system will call the first match, all right?

**Comment by SethTisue** [comment]
yes, I think that would be preferable. I think a pull request with this change would be accepted

**Comment by jvican** [comment]
In the unix case this is not preferable since putting `$SCALA_HOME/bin` before the rest of the previous `PATH` poses a security problem and makes it easier for an attacker to replace common utilities like `ls` or `echo` or `cat`. I think it's a convention to always add path entries to the end, not at the beginning.

**Comment by SethTisue** [comment]
Interesting, I've been doing the opposite for 25 years. A few minutes of googling doesn't turn up a clear consensus either way.

**Comment by NthPortal** [comment]
I'm with @jvican here. The only good reason I see to put it first is if you're trying to replace a normal system executable with one of your own (e.g. if you would like to use a newer version of Python 3 than the system has installed). However, you should be aware of the security trade-offs as Jorge mentioned.

**Comment by Philippus** [comment]
Let's close this and leave things as they are?
