### ISSUE TITLE
Code of Conduct's instructions on contacting a moderator don't work well

### ISSUE THREAD

**Issue by NthPortal** [scala/scala-lang#953]
(mostly copied from [Gitter](https://gitter.im/scala/center?at=5b9c36b8d655361f76feae3a))

When discussing how to contact moderators, the [Code of Conduct](https://scala-lang.org/conduct/) links to the 'about' page on Contributors, and to the Scala Center website. The latter does not have any way to privately message member of the Scala Center at all (barring the twitters of some of the developers, which I would be reticent to DM). The 'about' page on Contributors seems initially useful, but really isn't great:

- most people are listed under "Admins" rather than "Moderators", and it is perhaps not 100% clear that the former is a subset of the latter (Admins could potentially just be people who take care of logistical stuff to make sure the site stays running, but don't moderate)
- You can't PM anyone until you get the 'Basic' badge, which means that you have to do a whole bunch of interaction on Contributors (reading threads, and perhaps other stuff? the exact requirements aren't clear to me) before you can contact a moderator about your issue. At least personally, I didn't get the badge until a month after joining (you shouldn't even need to sign up for the forum at all in order to contact a moderator, but honestly even lifting the 'Basic' restriction is much better than what we have now)
- it might also be preferable to have a way to contact moderators without having to choose a specific person from a whole list of people. I don't think we should remove the option to choose a specific person to contact, but it would be nice to also be able to just "contact the moderation team"

**Comment by SethTisue** [comment]
totally agree we need to improve this in the reasonably near term

**Comment by NthPortal** [comment]
Is there a status update on this?

**Comment by SethTisue** [comment]
not that I've heard about

I guess for now if something arises, we:

1) refer the person to this ticket, to show we're aware that improvement is needed
2) tell them the de facto first point of contact for now is me, seth.tisue@lightbend.com (or @adriaanm)
3) if Adriaan and I are precisely the people they _don't_ want to talk to, we would contact the Scala Center, tell them there's a problem we can't handle, and then someone from Scala Center would contact the person

that's the status quo for now.

**Comment by adriaanm** [comment]
@sjrd, I suggest the scala center publishes/creates an email address that people can use to contact regarding code-of-conduct/moderation issues

**Comment by adriaanm** [comment]
ping @sjrd

**Comment by NthPortal** [comment]
don't mean to nag, but it has been 4.5 months.

**Comment by sjrd** [comment]
Thanks for the reminder. I've put it in my short-todo-list for today.

**Comment by sjrd** [comment]
FTR, this is going through the processes at EPFL. Creating a new top-level, EPFL-wide e-mail address needs to go through a few people.

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala-lang/pull/1011
