### ISSUE TITLE
broken links to Scalameta

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#955]
seen at https://travis-ci.org/scala/scala-lang/builds/431055044

```
- ./_site/blog/2016/10/24/scalafix.html
  *  External link http://scalameta.org/tutorial/ failed: 404 No error
- ./_site/blog/2017/10/09/scalamacros.html
  *  External link http://scalameta.org/paradise/ failed: 404 No error
```

**Comment by olafurpg** [comment]
Thanks for the ping, in my rush to get out the new site I had forgotten about the old one 😅 

I've updated https://scalameta.org/tutorial to forward to the new landing page. It may take a while to sync, please let me know if that fixes the 404s.

**Comment by ashawley** [comment]
The Paradise link is still 404.  Should that be fixed?

**Comment by olafurpg** [comment]
I didn't notice there was a link for paradise as well. I've added a small index.html for that url as well https://scalameta.org/paradise/

**Comment by ashawley** [comment]
Awesome, thanks!

**Comment by olafurpg** [comment]
Thank you for catching the broken links 😊

**Comment by ashawley** [comment]
Fixed in https://travis-ci.org/scala/scala-lang/builds/432498571

This issue can be closed.
