### ISSUE TITLE
Sharing blog posts on Twitter

### ISSUE THREAD

**Issue by ashawley** [scala/scala-lang#964]
The Twitter game is less good than I remember.

Posting links to the blog has a gray icon.

![Twitter post 10:17 AM - 4 Oct 2018](https://user-images.githubusercontent.com/358615/46969349-c76e7c00-d083-11e8-8889-d45703ee9200.png)

May require more meta tags:

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary.html

> `twitter:image`
> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 1:1 with minimum dimensions of 144x144 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. The image will be cropped to a square on all platforms. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

This image is specified on the Scala site by the Open Graph meta tag:

https://www.scala-lang.org/resources/img/scala-spiral-3d-2-toned-down.png

Running it through Twitter's validator,

```
INFO:  Page fetched successfully
INFO:  10 metatags were found
INFO:  twitter:card = summary tag found
ERROR: Possibly invalid value (if specified) (og:title)
ERROR: Possibly invalid value (if specified) (twitter:text:title)
ERROR: Possibly invalid value (if specified) (twitter:title)
```

Here's Twitter's card validator:

https://cards-dev.twitter.com/validator

Twitter is trying to tell us to fix something and punishing with a bad logo?   Maybe just fix the `og:title`, and the images might start working?

**Comment by Philippus** [comment]
looks like the "og:image" tag requires a full URL:
https://stackoverflow.com/questions/9858577/open-graph-can-resolve-relative-url
right now we're filling it with a relative url.

**Comment by ashawley** [comment]
That's interesting and good to know. I believe other pages use the relative url for the image and it's OK on Twitter.  The `og:title` is probably the fix here, but I see no reason not to fix both issues.

**Comment by Philippus** [comment]
`og:title` looks fine on blog posts like https://www.scala-lang.org/blog/2018/10/04/scaladoc-tables.html, and passed the twitter card validator.
The main page doesn't though, can add a title for that.

**Comment by ashawley** [comment]
Strange I thought blog posts failed the validater but maybe I mixed it up.

**Comment by ashawley** [comment]
Looks better.  Thanks!

![Twitter post 10:17 AM - 4 Oct 2018](https://user-images.githubusercontent.com/358615/47579971-88f67e00-d91b-11e8-903b-e670ecfe2197.png)

**Comment by SethTisue** [comment]
thanks @ashawley for reporting and @Philippus for fixing, seemingly small things like this really do help Scala come off well, IMO
