### ISSUE TITLE
Upgrade jekyll to version 3.8.5

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-lang#973]
would someone like to take a stab at this...? perhaps it will be easy or even trivial

**Comment by RichardMarto** [comment]
The docker-compose.yml are just getting the latest version of jekyll/jekyll image. Maybe I can upgrade jekyll at jekyll/jekyll repository.

**Comment by Philippus** [comment]
Here's an example of an earlier upgrade that was done: https://github.com/scala/scala-lang/pull/940
